// @generated by dev/tools/hidden_surface.py (release probe); do not edit.
#![allow(dead_code, unused_imports, unused_variables)]

fn main() {}

// hs_probe 0: function hs_fixture::Thing::debug_impl_method
fn hs_probe_0() {
    let _ = hs_fixture::Thing::debug_impl_method;
}

// hs_probe 1: impl hs_fixture::Thing::impl hs_fixture::DebugOnlyTrait
fn hs_probe_1() {
    fn hs_bound<T: ?Sized + hs_fixture::DebugOnlyTrait>() {}
    hs_bound::<hs_fixture::Thing>();
}

// hs_probe 2: function hs_fixture::all_gate
fn hs_probe_2() {
    use hs_fixture::all_gate as _;
}

// hs_probe 3: function hs_fixture::any_gate
fn hs_probe_3() {
    use hs_fixture::any_gate as _;
}

// hs_probe 4: function hs_fixture::cfg_drop_probe
fn hs_probe_4() {
    use hs_fixture::cfg_drop_probe as _;
}

// hs_probe 5: function hs_fixture::cfg_narrow_probe
fn hs_probe_5() {
    use hs_fixture::cfg_narrow_probe as _;
}

// hs_probe 6: function hs_fixture::cfg_probe
fn hs_probe_6() {
    use hs_fixture::cfg_probe as _;
}

// hs_probe 7: function hs_fixture::debug_only_for_test
fn hs_probe_7() {
    use hs_fixture::debug_only_for_test as _;
}

// hs_probe 8: function hs_fixture::debug_reexported
fn hs_probe_8() {
    use hs_fixture::debug_reexported as _;
}

// hs_probe 9: function hs_fixture::gate_both_probe
fn hs_probe_9() {
    use hs_fixture::gate_both_probe as _;
}

// hs_probe 10: module hs_fixture::release_only_proof
fn hs_probe_10() {
    use hs_fixture::release_only_proof as _;
}
