// @generated by dev/tools/hidden_surface.py (release probe); do not edit.
#![allow(dead_code, unused_imports, unused_variables)]

fn main() {}

// hs_probe 0: external hs_facade::debug_only_for_test
fn hs_probe_0() {
    use hs_facade::debug_only_for_test as _;
}

// hs_probe 1: module hs_facade::facade_release_proof
fn hs_probe_1() {
    use hs_facade::facade_release_proof as _;
}
