/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Embed a batch with the pinned default BGE-small model using CLS pooling.
 *
 * This is the TypeScript peer of Python's module-level `embed_batch_cls`.
 * It is deliberately distinct from [`Engine::embed`], which uses the
 * engine's Mean-pooling read path. Work runs on a blocking worker so the Node
 * event loop remains available while model loading or the forward pass runs.
 */
export declare function embedBatchCls(texts: Array<string>): Promise<Array<Array<number>>>
/** One caller-supplied passage accepted by standalone reranking. */
export interface RerankPassageInput {
  id: number
  body: string
  score: number
}
/** One standalone reranking result in final order. */
export interface RerankResult {
  id: number
  score: number
  ceScore?: number
}
/**
 * Rerank an arbitrary caller-supplied passage pool with the engine CE helper.
 *
 * `rerank_depth == 0` or an empty input is a model-free identity path. Builds
 * without the default reranker retain that identity behavior for every depth.
 */
export declare function rerank(query: string, passages: Array<RerankPassageInput>, rerankDepth: number, alpha?: number | undefined | null, poolN?: number | undefined | null): Promise<Array<RerankResult>>
export interface WriteReceipt {
  cursor: number
  /**
   * G0 (Slice 15) — per-row `write_cursor`s, 1:1 with the input batch order
   * (surfaced as `rowCursors`). Each `u64` is narrowed to `i64` at the FFI
   * boundary, matching the existing `cursor` cast.
   */
  rowCursors: Array<number>
  /**
   * G8 (Slice 20) — count of edge endpoints in this batch pointing at a
   * non-existent or superseded canonical node (surfaced as
   * `danglingEdgeEndpoints`; informational, flag-and-count). Narrowed `u64 →
   * i64` at the FFI boundary, matching the `cursor`/`rowCursors` precedent.
   */
  danglingEdgeEndpoints: number
}
export interface SourceDependencyV1 {
  schemaVersion: number
  dependencyId: string
  sourceRevisionId: string
  derivedRevisionId: string
  registeredDependencyGeneration: string
}
export interface ActuationReceiptV1 {
  schemaVersion: number
  operationId: string
  requestSha256: string
  outcome: string
  refusedOperationIndex?: number
  refusedFieldPath?: string
  reasonCodes: Array<string>
  affectedRevisionIds: Array<string>
  resultingWriteBoundary?: string
  resultingDependencyGeneration?: string
  pendingProjectionWriteCursors: Array<string>
  projectionGenerationId?: string
  closureOperationIds: Array<string>
}
export interface ProjectionGenerationStatusV1 {
  schemaVersion: number
  generationId: string
  declarationSha256: string
  origin: string
  transitionBoundary: string
  effectiveAtEpochS: number
  observedBoundary: string
  readyThrough: string
  readiness: string
  runtimeState: string
  pendingCount: string
  failedCount: string
}
export interface MutationProjectionStatusV1 {
  schemaVersion: number
  operationId: string
  writeCursor: string
  generationId: string
  effectiveAtEpochS: number
  observedBoundary: string
  readyThrough: string
  readiness: string
  runtimeState: string
  pendingCount: string
  failedCount: string
}
export interface DependencyListV1 {
  schemaVersion: number
  items: Array<SourceDependencyV1>
}
/**
 * 0.8.20 Slice 5d (R-20-E4) — outcome of the `eraseSource` lifecycle verb.
 * Mirrors the Rust `ExciseReport`. Counts are narrowed `u64 -> i64` at the FFI
 * boundary, matching the `WriteReceipt.cursor` precedent.
 */
export interface EraseReport {
  sourceRef: string
  nodesExcised: number
  edgesExcised: number
  /**
   * Row-owned projection rows (FTS5 + vec0 + `search_index_v2`) dropped
   * alongside the canonical rows.
   */
  projectionsInvalidated: number
}
/**
 * 0.8.20 Slice 15d (R-20-PR) — a declarative projection declaration. Flat at
 * the FFI boundary; `fts`/`vector` booleans carry the sub-object PRESENCE and
 * the optional tokenizer/embedder carry the value. JS field names are
 * camelCase (`ftsTokenizer` / `vectorEmbedder`).
 */
export interface ProjectionSpec {
  name: string
  roles: Array<string>
  fts: boolean
  ftsTokenizer?: string
  vector: boolean
  vectorEmbedder?: string
  /**
   * READ METADATA, engine-set (`vectorDenseReadiness` in JS):
   * `"unavailable"` / `"embedding"` / `"ready"` on the way OUT of
   * `read.projections`, omitted on every caller-authored spec.
   * `"unavailable"` means no usable dense runtime; the other values derive
   * from outstanding work under one. Inert on the way IN (the engine reports
   * the derived truth), so read output still re-applies as a no-op.
   */
  vectorDenseReadiness?: string
  /** Ordered literal object-member path; absent preserves top-level lookup. */
  source?: Array<string>
}
/** 0.8.20 Slice 15d (R-20-PR) — the diff `configureProjections` applied. */
export interface ProjectionDelta {
  built: Array<string>
  dropped: Array<string>
  deferred: Array<string>
  unchanged: boolean
  /**
   * 0.8.20 Slice 22 (R-20-VC / TC-67) — node KINDS the vector writer can never
   * commit. A different axis from the three attribute-name lists above; the
   * name says so. Output-only: `configureProjections` takes specs, never a
   * delta, so there is no inbound direction to round-trip.
   */
  vectorUnsupportedKinds: Array<string>
}
/** One declared projection's current dense status in the pure status facade. */
export interface ProjectionRuntimeStatusEntry {
  name: string
  /** `not_declared` / `unavailable` / `embedding` / `ready`. */
  denseReadiness: string
}
/** A pure current view of projection runtime facts for one open engine session. */
export interface ProjectionRuntimeStatus {
  runtimeEmbedderAvailable: boolean
  /** `none` / `no_runtime` / `vector_equivalence_disabled`. */
  runtimeUnavailabilityReason: string
  projections: Array<ProjectionRuntimeStatusEntry>
  vectorUnsupportedKinds: Array<string>
}
export interface EmbeddingReadiness {
  state: string
  usableEmbedder: boolean
  pendingCount: number
  affectedKinds: Array<string>
  code?: string
  operation?: string
  remediations: Array<string>
  documentationUrl?: string
}
/** G11 (Slice 15) — BYO-LLM ingest receipt. */
export interface IngestWithExtractorReceipt {
  nodesWritten: number
  edgesWritten: number
  docsProcessed: number
}
/** 0.8.12 Slice 15 (OPP-2) — BYO-LLM consolidation receipt. */
export interface ConsolidateReceipt {
  clustersProcessed: number
  edgesExamined: number
  edgesKept: number
  edgesInvalidated: number
  edgesSuperseded: number
}
export interface SoftFallback {
  /** "vector" | "text" | "text_edge" */
  branch: string
}
/**
 * C-2 (0.8.19 / OPP-12 Phase-1, TC-8) — the typed id-space carrier for
 * [`SearchHit::id`], surfaced to JS as `{ space, value }`. `space` is the
 * lowercase discriminant (`"logical"` | `"content"` | `"passage"`), mirroring
 * the engine's `IdSpaceKind` enum (the C-2 binding — a typed carrier, not a
 * magic-prefixed string). `value` is the bare id (id-space prefix stripped).
 */
export interface IdSpace {
  /** "logical" | "content" | "passage" */
  space: string
  /** The bare id value (id-space prefix stripped). */
  value: string
}
export interface SearchHit {
  /**
   * C-2 (0.8.19 / TC-8) — the typed, non-null, id-space-total hit id
   * (`{ space, value }`). Governed hits are `logical` (`"l:"`), doc-seeded hits
   * `content` (`"h:"`), synthetic passages `passage` (`"p:"`). Its `value`
   * equals the pre-0.8.19 `stableId` (which this subsumes) so cross-session
   * real-gold keying continues on `id`. The pre-C-2 positional `write_cursor`
   * id is engine-internal and no longer surfaced.
   */
  id: IdSpace
  kind: string
  body: string
  /**
   * Raw per-branch relevance: `vec_distance_l2` (vector) or `bm25()`
   * (text). Not comparable across branches raw.
   */
  score: number
  /** "vector" | "text" */
  branch: string
  /**
   * Source-document provenance (`sourceId` in JS) — the identifier
   * `eraseSource` consumes. TC-31 (0.8.20): populated on EVERY hit path, not
   * just the graph arm. Node hits (text/vector) carry the node's own
   * `source_id`; edge hits (edge-FTS, vector edge-fact) carry the edge's own;
   * graph-arm hits carry the traversed edge's (unchanged). `null` only when
   * the stored row really has NULL provenance: written before 0.8.20, or a
   * governed row spared by the step-21 backfill under the TC-11 pin.
   */
  sourceId?: string
  /**
   * 0.8.5 (EXP-0) — per-candidate CE score `ce_norm = sigmoid(ce_logit)`
   * (`ceScore` in JS). Set only for hits inside the reranked pool; `null`
   * otherwise (out-of-pool, identity path, or no CE model loaded).
   */
  ceScore?: number
}
/**
 * Slice 30 (G2) — an active canonical node row from `read.get` /
 * `read.getMany`. napi maps snake_case → camelCase JS (`logicalId`,
 * `writeCursor`).
 */
export interface NodeRecord {
  logicalId: string
  kind: string
  body: string
  writeCursor: number
}
/**
 * Slice 30 (G3) — one `operational_mutations` row from `read.collection` /
 * `read.mutations`. `id` is the after-id cursor key. napi maps snake_case →
 * camelCase JS (`recordKey`, `opKind`, `schemaId`, `writeCursor`).
 */
export interface OpStoreRow {
  id: number
  collection: string
  recordKey: string
  opKind: string
  payload: string
  schemaId?: string
  writeCursor: number
}
export interface OperationalStateRecordV1 {
  schemaVersion: number
  collection: string
  recordKey: string
  payload: string
  schemaId?: string
  writeCursor: number
}
export interface PageRequestV1 {
  schemaVersion: number
  limit: number
  cursor?: string
}
export interface NodePageV1 {
  schemaVersion: number
  items: Array<NodeRecord>
  nextCursor?: string
}
export interface OperationalStatePageV1 {
  schemaVersion: number
  items: Array<OperationalStateRecordV1>
  nextCursor?: string
}
/**
 * G10 — closed metadata filter input for `search(query, filter?)`. All fields
 * optional; an all-`None` filter (or omitted) is the unfiltered path. Mirrors
 * the Python `SearchFilter` (cross-binding parity). napi maps the snake_case
 * fields to camelCase JS (`sourceType`, `createdAfter`).
 */
export interface SearchFilterInput {
  sourceType?: string
  kind?: string
  createdAfter?: number
  status?: string
  /** Ordered `[projectionName, canonicalText]` pairs. */
  attributes?: Array<Array<string>>
}
export interface SearchResult {
  projectionCursor: number
  softFallback?: SoftFallback
  results: Array<SearchHit>
  /**
   * 0.8.8 EXP-OBS (Slice 10) — opt-in retrieval explanation sidecar
   * (`explanation` in JS). Present only when `search(..., explain=true)`; `null`
   * (default) keeps the payload byte-identical to the pre-0.8.8 shape.
   */
  explanation?: Explanation
}
export interface EvidenceSidecarEntryV1 {
  schemaVersion: number
  resultIndex: number
  artifactRevisionId: string
  evidenceRef: string
}
export interface EvidenceSearchResultV1 {
  schemaVersion: number
  searchResult: SearchResult
  evidence: Array<EvidenceSidecarEntryV1>
}
export interface EvidenceContributionV1 {
  schemaVersion: number
  vectorRank?: number
  textRank?: number
  graphRank?: number
  fusedScore: number
  ceScore?: number
  blendedScore: number
  importance?: number
  confidence?: number
}
export interface EvidenceGraphOriginV1 {
  kind: string
  edgeArtifactRevisionId?: string
  hopCount?: number
}
export interface EvidenceProjectionOriginV1 {
  schemaVersion: number
  artifactClass: string
  representativeArm: string
  projectionGenerationId: string
  graphOrigin?: EvidenceGraphOriginV1
}
export interface EvidenceLocatorV1 {
  kind: string
  startInclusive?: string
  endExclusive?: string
}
export interface EvidenceArtifactLifecycleV1 {
  kind: string
  state?: string
  superseded: boolean
  validAtEffective?: boolean
}
export interface ResolvedEvidenceV1 {
  schemaVersion: number
  logicalId?: string
  artifactRevisionId: string
  sourceId: string
  sourceVersionId: string
  sourceRevisionId: string
  locator: EvidenceLocatorV1
  canonicalSourceBody: string
  evidenceText: string
  canonicalSourceHash: string
  effectiveValidAt: number
  artifactLifecycle: EvidenceArtifactLifecycleV1
  sourceLifecycleState: string
  projectionOrigin: EvidenceProjectionOriginV1
  retrievalContribution: EvidenceContributionV1
  dependency?: SourceDependencyV1
}
/**
 * 0.8.8 EXP-OBS (Slice 10) — query-level retrieval trace (mirror of engine
 * `QueryTrace`). napi maps snake_case → camelCase JS (`queryChars`,
 * `rerankDepth`, `useGraphArm`, `embedderId`, `ceActive`, `vectorHits`, …).
 */
export interface QueryTrace {
  queryChars: number
  k: number
  rerankDepth: number
  poolN: number
  alpha: number
  useGraphArm: boolean
  recency: boolean
  embedderId: string
  ceActive: boolean
  vectorHits: number
  textHits: number
  graphHits: number
  droppedEdgeHits: number
}
/**
 * 0.8.8 EXP-OBS (Slice 10) — per-hit provenance + score breakdown (mirror of
 * engine `PerHitExplain`). `id` is the hit's engine-internal positional
 * `write_cursor` (the pre-0.8.19 `SearchHit.id`), `as i64` → JS number (NO
 * BigInt/string promotion). Post-C-2 the caller-facing `SearchHit.id` is the
 * typed `{ space, value }` object; correlate a `PerHitExplain` to its `SearchHit`
 * by position (both arrays are 1:1, same order). napi maps snake_case →
 * camelCase (`vectorRank`, `fusedScore`, `ceScore`).
 */
export interface PerHitExplain {
  id: number
  arm: string
  vectorRank?: number
  textRank?: number
  graphRank?: number
  fusedScore: number
  ceScore?: number
  blended: number
  /**
   * 0.8.16 Slice 5 / F9 — node importance / edge confidence applied to this
   * hit's contribution (`None` = graceful-absent / neutral). Mirrors the
   * engine `PerHitExplain` additive fields (napi → `importance`, `confidence`).
   */
  importance?: number
  confidence?: number
  structural: StructuralInclusionV1
}
export interface StructuralInclusionV1 {
  schemaVersion: number
  inclusionState: string
  projectionOrigin: string
  dependencyState: string
  lifecycleState: string
  degradationCodes: Array<string>
}
/**
 * 0.8.8 EXP-OBS (Slice 10) — the explanation sidecar (mirror of engine
 * `Explanation`): a query-level [`QueryTrace`] + a per-hit breakdown parallel to
 * (and in the same order as) `SearchResult.results`.
 */
export interface Explanation {
  trace: QueryTrace
  perHit: Array<PerHitExplain>
  correlationId: string
}
export interface MigrationStepReport {
  stepId: number
  durationMs?: number
  failed: boolean
}
export interface EmbedderIdentity {
  name: string
  revision: string
  dimension: number
}
/**
 * EU-6 — discriminated-union shape for `OpenReport.embedderEvents`.
 *
 * `kind` carries the variant name (`"DefaultEmbedderDownload"`,
 * `"DefaultEmbedderCacheHit"`, `"MeanVecPinned"`); the remaining
 * optional fields carry the variant payload in camelCase. We pick a
 * flat object (rather than a per-variant `#[napi]` class) so callers
 * can pattern-match on `event.kind` without importing leaf classes.
 */
export interface EmbedderEvent {
  kind: string
  file?: string
  url?: string
  bytes?: number
  sha256?: string
  cachePath?: string
  durationMs?: number
  dim?: number
  docCount?: number
  /**
   * 0.7.2 PR-2b — `"manual"` on `MeanVecRecomputed` (the automatic
   * `"drift_auto"` trigger was carved out / deferred to 0.8.x).
   */
  trigger?: string
  /**
   * Reserved (always `None` as of 0.7.2 PR-2bc — the `MeanRecomputeDeferred`
   * event that carried this was removed with the automatic drift path).
   */
  driftCos?: number
}
/** Safe CUDA provider facts associated with an effective CUDA selection. */
export interface CudaDeviceInfo {
  ordinal: number
  uuid?: string
  name?: string
  driverVersion?: string
  computeCapability?: string
  cudaToolkitVersion?: string
}
/** Process-visible CUDA identity facts preserved in an open report. */
export interface CudaVisibleDevice {
  visibleOrdinal: number
  uuid: string
  name: string
  computeCapability?: string
}
/** The CPU or CUDA backend selected for one embedder device policy. */
export interface EffectiveEmbedDevice {
  /** Either `"cpu"` or `"cuda"`. */
  kind: string
  /** Present exactly when `kind == "cuda"`. */
  cudaDevice?: CudaDeviceInfo
}
/** The strict CPU/CUDA policy outcome captured when an embedder was constructed. */
export interface EmbedderDeviceResolution {
  requestedPolicy: string
  cudaCompiled: boolean
  effectiveDevice: EffectiveEmbedDevice
  visibleCudaDevices: Array<CudaVisibleDevice>
  selectedCudaUuid?: string
  reason?: string
}
/**
 * 0.8.23 Slice 80.6 (D-80.6-6, R80-13) — the retained
 * `fathomdb.tegra-gpu-allocation-witness/v1` record, measured in the
 * artifact's own process.
 *
 * Every number the verdict used is carried, so a reader re-derives the
 * verdict instead of trusting it: the raw free-memory samples that bracket
 * the model load, the declared floor they were judged against, and the
 * deliberate control allocation that proves the shared iGPU counter was live
 * and attributable at the time. Dropping any of them would leave a consumer
 * able to report a pass it cannot check.
 */
export interface GpuAllocationWitness {
  /** Schema string of the retained record. */
  schema: string
  /** The precondition the witness run states rather than assumes. */
  soleGpuConsumerPrecondition: string
  deviceOrdinalRequested: number
  deviceOrdinalActual: number
  deviceUuid: string
  deviceName: string
  computeCapability: string
  freeBeforeBytes: number
  freeAfterBytes: number
  totalBytes: number
  deltaBytes: number
  deltaFloorBytes: number
  controlAllocationRequestBytes: number
  controlBlockCount: number
  controlFreeBeforeBytes: number
  controlFreeAfterBytes: number
  controlDeltaBytes: number
  embeddedVectorDim: number
}
export interface OpenReport {
  schemaVersionBefore: number
  schemaVersionAfter: number
  migrationSteps: Array<MigrationStepReport>
  embedderWarmupMs: number
  queryBackend: string
  defaultEmbedder: EmbedderIdentity
  embedderDownloadMs?: number
  embedderEvents: Array<EmbedderEvent>
  embedderMeanCenteringRequired: boolean
  embedderMeanVecPinned: boolean
  /**
   * 0.8.18 Slice 5 (#5 vector-equivalence probe, R-VEQ-6) — `true` iff the
   * open-time #5 self-check found a vector-equivalence divergence beyond the
   * D4 floor and every vector-dependent arm now refuses at query time with a
   * `FDB_VECTOR_EQUIVALENCE_MISMATCH` error. The text-only/FTS-only path
   * (`searchTextOnly`) stays serviceable.
   */
  denseDisabled: boolean
  /** R-VEQ-6 — human-readable reason for `denseDisabled`, or `null` when healthy. */
  denseDisabledReason?: string
  /**
   * Strict CPU/CUDA selection used to construct the embedder, or `null` when
   * no embedder was configured.
   */
  embedderDeviceResolution?: EmbedderDeviceResolution
  rerankerDeviceResolution?: EmbedderDeviceResolution
  /**
   * 0.8.23 Slice 80.6 (D-80.6-6, AC80-6) — the in-process GPU allocation
   * witness, or `null` when this open measured none.
   *
   * `null` means **no witness was taken**, never "a witness measured
   * nothing": a zero, negative, or below-floor allocation delta is a typed
   * failure inside the witness and fails the open, so a zero-valued record
   * is not reachable here.
   */
  embedderGpuAllocationWitness?: GpuAllocationWitness
}
export interface CounterSnapshot {
  queries: number
  writes: number
  writeRows: number
  adminOps: number
  cacheHit: number
  cacheMiss: number
}
export interface AttachSubscriberOptions {
  heartbeatIntervalMs?: number
}
export interface EngineConfig {
  embedderPoolSize?: number
  schedulerRuntimeThreads?: number
  provenanceRowCap?: number
  embedderCallTimeoutMs?: number
  slowThresholdMs?: number
}
export interface EngineOpenOptions {
  engineConfig?: EngineConfig
  /**
   * EU-6: opt-in to the engine's pinned default embedder
   * (`fathomdb-bge-small-en-v1.5`). On first use, weights are
   * downloaded from HuggingFace and cached under
   * `~/.cache/fathomdb/embedders/`. `false` (the default) opens
   * without an embedder; vector writes then fail with
   * `EmbedderNotConfigured`.
   */
  useDefaultEmbedder?: boolean
}
export interface AdminConfigureOptions {
  name: string
  body: string
}
export interface RuntimeConfigureOptions {
  sqliteMode: string
}
export interface RuntimeConfiguration {
  sqliteMode: string
}
export declare function adminConfigureRuntime(options: RuntimeConfigureOptions): RuntimeConfiguration
export declare function adminConfigure(engine: Engine, options: AdminConfigureOptions): Promise<WriteReceipt>
/**
 * Slice 30 (G3) — options for `read.collection` / `read.mutations`. `limit` is
 * MANDATORY (no default — the engine clamps it to the ~1M cap); `afterId` is
 * the exclusive cursor.
 * 0.8.20 Slice 10b (R-20-RV / R-20-NV) — the TypeScript face of `ReadView`.
 *
 * Idiomatic `camelCase`; every field is optional and every one defaults to the
 * STRICT view, so omitting `view` entirely reproduces the shipped read
 * behaviour exactly.
 *
 * World-time only — there is deliberately no `historyAsOf`.
 */
export interface ReadViewInput {
  /** Relax `superseded_at IS NULL` — include historical versions. */
  includeSuperseded?: boolean
  /** Relax `state = 'active'` — include non-active lifecycle states. */
  includeInactive?: boolean
  /** Relax the validity window entirely (ignores `validAsOf`). */
  includeOutOfWindow?: boolean
  /** Validity instant, INTEGER epoch SECONDS. Omitted = now. */
  validAsOf?: number
}
/** Versioned validity and eligibility request for a frozen read context. */
export interface ReadContextV1 {
  schemaVersion: number
  view: ReadViewInput
  eligibility: SearchFilterInput
}
/** Engine-minted database-local authenticated read context. */
export interface FrozenReadContextV1 {
  schemaVersion: number
  effectiveValidAt: number
  context: ReadContextV1
  token: string
}
/** 0.8.20 Slice 10b (R-20-NV) — the TypeScript face of `BoundaryCrossing`. */
export interface BoundaryCrossing {
  /** The node that crossed a validity boundary. */
  node: NodeRecord
  /** Set when the node BECAME VALID inside the interrogated interval. */
  becameValidAt?: number
  /** Set when the node BECAME INVALID inside the interrogated interval. */
  becameInvalidAt?: number
}
export interface ReadCollectionOptions {
  afterId?: number
  limit: number
}
export declare function readGet(engine: Engine, logicalId: string, view?: ReadViewInput | undefined | null): Promise<NodeRecord | null>
export declare function readGetMany(engine: Engine, logicalIds: Array<string>, view?: ReadViewInput | undefined | null): Promise<Array<NodeRecord | undefined | null>>
export declare function readCollection(engine: Engine, collection: string, options: ReadCollectionOptions): Promise<Array<OpStoreRow>>
export declare function readMutations(engine: Engine, collection: string, options: ReadCollectionOptions): Promise<Array<OpStoreRow>>
/**
 * G4 (Slice 35) — predicate input for `readList`. Shape mirrors the TS
 * `Predicate` interface: `type` ∈ `{"eq","gt","gte","lt","lte"}`, `path`,
 * `value` (JS `string | number | boolean` — carried as `f64` for numbers).
 */
export interface PredicateInput {
  /** Comparison type: "eq" | "gt" | "gte" | "lt" | "lte". */
  type: string
  /** JSON path from the allowlist (e.g. "$.status", "$.priority"). */
  path: string
  /** String value for eq/gt/gte/lt/lte string comparisons. */
  valueStr?: string
  /** Integer value for numeric comparisons. */
  valueInt?: number
  /** Boolean value for bool comparisons. */
  valueBool?: boolean
}
export declare function readList(engine: Engine, kind: string, predicates?: Array<PredicateInput> | undefined | null, limit?: number | undefined | null, view?: ReadViewInput | undefined | null): Promise<Array<NodeRecord>>
/**
 * 0.8.11 Slice 40 (#17) — one term of the unified `Filter` grammar. `term` ∈
 * `{"source_type","kind","created_after","status","json"}`. For the four
 * shorthand terms set `valueStr`/`valueInt`; for `json` set `predicate`.
 */
export interface FilterTermInput {
  /** Discriminator: source_type | kind | created_after | status | json. */
  term: string
  /** String value for source_type/kind/status terms. */
  valueStr?: string
  /** Integer value for the created_after term (unix seconds). */
  valueInt?: number
  /** The G4 predicate for a `json` term. */
  predicate?: PredicateInput
}
/**
 * 0.8.11 Slice 40 (#17) — unified `Filter` → `read.list` backend. The engine
 * performs the authoritative total dispatch (Json `json_extract`;
 * SourceType/Kind constant-fold vs the partition kind).
 */
export declare function readListFilter(engine: Engine, kind: string, terms?: Array<FilterTermInput> | undefined | null, limit?: number | undefined | null, view?: ReadViewInput | undefined | null): Promise<Array<NodeRecord>>
export declare function readCanonicalPage(engine: Engine, kind: string, context: FrozenReadContextV1, page: PageRequestV1): Promise<NodePageV1>
export declare function readOperationalState(engine: Engine, collection: string, recordKey: string, context?: FrozenReadContextV1 | undefined | null): Promise<OperationalStateRecordV1 | null>
export declare function readOperationalStatePage(engine: Engine, collection: string, context: FrozenReadContextV1, page: PageRequestV1): Promise<OperationalStatePageV1>
/**
 * Slice 20 — one expanded node entry in `SearchExpandResult.expanded`.
 * `hopCount` is the BFS distance from the nearest search-hit root.
 */
export interface ExpandedNode {
  node: NodeRecord
  hopCount: number
}
/**
 * Slice 20 (G6) — result of `searchExpand`.
 *
 * `searchHits` — original RRF-scored results from the search step.
 * `expanded`   — nodes reachable from any hit within `depth` hops that are
 *                NOT in `searchHits` (deduplication: search score wins).
 * `allLogicalIds` — deduplicated union of both sets.
 */
export interface SearchExpandResult {
  searchHits: Array<SearchHit>
  expanded: Array<ExpandedNode>
  allLogicalIds: Array<string>
}
/**
 * Slice 20 (G5) — bounded BFS from `logicalId` over `canonical_edges`.
 *
 * `depth` must be 1–3; rejects depth > 3 with `InvalidArgumentError`.
 * `direction` is `"outgoing"`, `"incoming"`, or `"both"`.
 * Returns up to 50 `NodeRecord`s reachable within `depth` hops.
 * Edges with `t_invalid` in the past are not traversed.
 */
export declare function graphNeighbors(engine: Engine, logicalId: string, depth: number, direction: string, view?: ReadViewInput | undefined | null): Promise<Array<NodeRecord>>
/**
 * 0.8.20 Slice 10b (R-20-NV) — nodes that crossed a validity boundary in
 * `(since, view-instant]`. `since` is INTEGER epoch SECONDS.
 */
export declare function crossedBoundarySince(engine: Engine, since: number, view?: ReadViewInput | undefined | null): Promise<Array<BoundaryCrossing>>
/**
 * Slice 20 (G6) — FTS/vector search followed by bounded BFS expansion.
 *
 * Runs `search(query, filter)` (G1), then expands each hit via
 * `graph_neighbors(depth, both)`. Nodes appearing in both sets appear
 * only in `searchHits` (deduplication: search score takes priority).
 */
export declare function searchExpand(engine: Engine, query: string, depth: number, sourceType?: string | undefined | null, kind?: string | undefined | null, createdAfter?: number | undefined | null, status?: string | undefined | null, searchLimit?: number | undefined | null): Promise<SearchExpandResult>
export declare class Engine {
  /**
   * Promise-returning open per `dev/interfaces/typescript.md`. The
   * blocking SQLite work runs on a tokio blocking thread.
   */
  static open(path: string, options?: EngineOpenOptions | undefined | null): Promise<Engine>
  /**
   * Structured open report captured at [`Engine::open`] time. Sync
   * accessor (no Promise — the data lives on the engine struct
   * after open). Idempotent: each call returns a fresh copy of the
   * same snapshot.
   */
  openReport(): OpenReport
  write(batch: Array<JsonValue>): Promise<WriteReceipt>
  actuate(request: JsonValue): Promise<ActuationReceiptV1>
  registerSourceDependency(request: JsonValue): Promise<SourceDependencyV1>
  dependenciesForSource(request: JsonValue): Promise<DependencyListV1>
  dependencyForDerived(request: JsonValue): Promise<SourceDependencyV1 | null>
  /** Return the current status for one opaque dependency-closure operation. */
  readDependencyClosure(request: JsonValue): Promise<JsonValue | null>
  /**
   * OPP-12 Phase-1 (0.8.19 Slice 10) — `transition` lifecycle verb. Thin
   * pass-through: enforces the legal-transition table + `reason`
   * clear-on-admit/set-on-exclude semantics (design §2/§3). Keys on the bare
   * `logicalId` (`l:` only); a non-`l:` id → `NotLifecycleAddressableError`; an
   * illegal move → `IllegalTransitionError { fromState, toState, legal }`.
   */
  transition(logicalId: string, toState: string, reason?: string | undefined | null): Promise<void>
  /**
   * OPP-12 Phase-1 (0.8.19 Slice 10) — `purge` lifecycle verb. Thin
   * pass-through: deleted-first, idempotent hard-erase across every row-owned
   * target (design §3). Keys on the bare `logicalId` (`l:` only); a non-`l:` id
   * → `NotLifecycleAddressableError`; a non-`deleted` node →
   * `IllegalTransitionError`.
   */
  purge(logicalId: string): Promise<void>
  /**
   * 0.8.20 Slice 5d (R-20-E4, design §4 item 9b) — `eraseSource` lifecycle
   * verb. Deletes every canonical row carrying `sourceId`, plus its
   * row-owned projections, and finishes the erasure at rest.
   *
   * The COMPANION to `purge`, not a duplicate: `purge` addresses a governed
   * node by `logicalId`; `eraseSource` addresses ANONYMOUS content (rows
   * with no `logicalId`) by its provenance, which `purge` cannot reach.
   * Together they make every canonical row erasable from the SDK alone,
   * with no CLI on `PATH`.
   *
   * Idempotent (an absent source is a zero-count success). Throws
   * `WriteValidationError` for an empty, whitespace-only or reserved
   * (`_`-prefixed) `sourceId`. NOT a recovery-denylist name — AC-041 holds.
   */
  eraseSource(sourceId: string): Promise<EraseReport>
  /**
   * 0.8.20 Slice 15d (R-20-PR / C-1) — the `configureProjections` governed
   * verb. Declarative + idempotent: the engine diffs `specs` against the
   * durable registry and backfills the difference. `drop` is EXPLICIT
   * (omission never drops); a destructive change to a live projection without
   * a drop throws a `FDB_PROJECTION_DESTRUCTIVE` error carrying `{name, delta}`.
   */
  configureProjections(specs: Array<ProjectionSpec>, drop?: Array<string> | undefined | null): Promise<ProjectionDelta>
  /**
   * 0.8.20 Slice 15d (R-20-PR) — `read.projections` introspection. Returns
   * every declared `ProjectionSpec` (sorted by name).
   */
  readProjections(): Promise<Array<ProjectionSpec>>
  /**
   * Read current projection-runtime facts without changing configuration or
   * scheduling work. This pure query may take the ordinarily opened engine
   * connection lock; it is not a `ReaderWorkerPool` request and does not open
   * a separately read-only SQLite connection. This is the native peer of
   * `read.projectionStatus`.
   */
  readProjectionStatus(): Promise<ProjectionRuntimeStatus>
  readProjectionGenerationStatus(): Promise<ProjectionGenerationStatusV1>
  readMutationProjectionStatus(request: JsonValue): Promise<MutationProjectionStatusV1>
  readEmbeddingReadiness(): Promise<EmbeddingReadiness>
  /** Mint a restart-stable authenticated read context. */
  freezeReadContext(context: ReadContextV1): Promise<FrozenReadContextV1>
  /** Validate a frozen context before JavaScript converts dynamic controls. */
  validateFrozenReadContext(context: FrozenReadContextV1): Promise<void>
  /** Execute one canonical JSON graph-expansion request. */
  graphExpand(requestJson: string): Promise<string>
  /** Return canonical version-1 JSON for one governed dependency trace. */
  traceDependency(rootRevisionId: string, direction: string, context: FrozenReadContextV1, maxRelations?: number | undefined | null, maxWorkUnits?: number | undefined | null): Promise<string>
  /** Search under a frozen validity and eligibility context. */
  searchFrozen(query: string, context: FrozenReadContextV1, rerankDepth?: number | undefined | null, useGraphArm?: boolean | undefined | null, alpha?: number | undefined | null, poolN?: number | undefined | null, explain?: boolean | undefined | null, limit?: number | undefined | null): Promise<SearchResult>
  /** Search under a frozen context and attach one evidence reference per hit. */
  searchWithEvidence(query: string, context: FrozenReadContextV1, rerankDepth?: number | undefined | null, useGraphArm?: boolean | undefined | null, alpha?: number | undefined | null, poolN?: number | undefined | null, includeExplanation?: boolean | undefined | null, limit?: number | undefined | null): Promise<EvidenceSearchResultV1>
  /** Resolve exact source bytes under an equivalent frozen context. */
  resolveEvidence(evidenceRef: string, context: FrozenReadContextV1): Promise<ResolvedEvidenceV1>
  /** Resolve one exact artifact disclosed by frozen graph expansion. */
  resolveGraphEvidence(evidenceRef: string, context: FrozenReadContextV1): Promise<string>
  /** Search and expand on one frozen reader transaction. */
  searchExpandFrozen(query: string, context: FrozenReadContextV1, depth: number, limit?: number | undefined | null): Promise<SearchExpandResult>
  search(query: string, filter?: SearchFilterInput | undefined | null, rerankDepth?: number | undefined | null, useGraphArm?: boolean | undefined | null, alpha?: number | undefined | null, poolN?: number | undefined | null, explain?: boolean | undefined | null, view?: ReadViewInput | undefined | null, limit?: number | undefined | null): Promise<SearchResult>
  /** Lexically search one declared property-FTS projection only. */
  searchProjectedText(query: string, name: string, filter?: SearchFilterInput | undefined | null, view?: ReadViewInput | undefined | null, limit?: number | undefined | null): Promise<SearchResult>
  /**
   * 0.8.18 Slice 5 (#5 vector-equivalence probe, R-VEQ-4) — the explicit
   * text-only / FTS-only search path. Does NOT embed the query and NEVER raises
   * `FDB_VECTOR_EQUIVALENCE_MISMATCH`, so it stays serviceable when the engine
   * opened in the degraded `denseDisabled` state. Matching node- and edge-body
   * FTS candidates are deterministically body-deduplicated and ranked before
   * `limit`; no vector recall, CE rerank, or graph arm runs on this path.
   *
   * 0.8.20 Slice 15b fix-2 — takes the same optional `view` as `search`.
   */
  searchTextOnly(query: string, view?: ReadViewInput | undefined | null, limit?: number | undefined | null): Promise<SearchResult>
  /**
   * 0.8.18 Slice 5 (R-VEQ-6) — `true` iff the engine opened degraded (the #5
   * self-check found a vector-equivalence divergence and every dense arm is
   * refusing). Mirrors `OpenReport.denseDisabled`.
   */
  denseDisabled(): boolean
  /**
   * 0.8.18 Slice 5 (R-VEQ-6) — the human-readable reason for the degraded state,
   * or `null` when dense is healthy.
   */
  denseDisabledReason(): string | null
  /**
   * 0.8.18 Slice 5 (R-VEQ-6) — telemetry counter: query-time dense-arm refusals
   * raised because the engine opened degraded.
   */
  vectorEquivalenceRefusalCount(): number
  close(): Promise<void>
  drain(timeoutMs: number): Promise<void>
  /**
   * 0.8.8 Slice 15 (OPP-9) — enable opt-in local telemetry capture to a JSONL
   * `sinkPath`. Off by default; local file only (no egress).
   */
  enableTelemetry(sinkPath: string): Promise<void>
  /**
   * 0.8.8 Slice 15 — the most-recent captured `queryId` (for `recordFeedback`),
   * or `null` when telemetry is off / no query captured yet.
   */
  lastTelemetryQueryId(): string | null
  /**
   * 0.8.8 Slice 15 — attach agent relevance labels for a captured `queryId`.
   * Ids are the positional `write_cursor` keys emitted in the telemetry
   * `result_ids` array (the pre-0.8.19 `SearchHit.id` space), NOT the post-C-2
   * typed `SearchHit.id`. Errors if telemetry is off.
   */
  recordFeedback(queryId: string, relevantIds: Array<number>, irrelevantIds: Array<number>, labelSource: string): Promise<void>
  /**
   * G11 (Slice 15) — BYO-LLM ingest. `cmd` is the argv to spawn (first
   * element = program, rest = args). `documents` is an array of objects
   * with `sourceDocId` and `body` string properties.
   */
  ingestWithExtractor(cmd: Array<string>, documents: Array<JsonValue>): Promise<IngestWithExtractorReceipt>
  /**
   * 0.8.12 Slice 15 (OPP-2) — BYO-LLM consolidation. `cmd` is the argv to
   * spawn a caller-supplied harness speaking `fathomdb.consolidate.v1` (the
   * SAME transport as extraction). `axes` is an array of objects with
   * `subjectLogicalId` and `relation` string properties. FathomDB assembles
   * each competing fact-edge cluster deterministically and applies the harness
   * verdicts as supersession/recency metadata (bodies never rewritten).
   */
  consolidateWithProvider(cmd: Array<string>, axes: Array<JsonValue>): Promise<ConsolidateReceipt>
  /**
   * Embed `text` with the engine's pinned default embedder
   * (`fathomdb-bge-small-en-v1.5`) and return the raw vector.
   *
   * Read-path primitive (mirror of the Python `Engine.embed`) for callers
   * that need vectors under the engine's own embedder identity (e.g.
   * coverage-index clustering) rather than a parallel, possibly-divergent
   * embedder. Rejects with `FDB_EMBEDDER_NOT_CONFIGURED` if the engine was
   * opened without an embedder (`useDefaultEmbedder: false`).
   */
  embed(text: string): Promise<Array<number>>
  counters(): CounterSnapshot
  setProfiling(enabled: boolean): void
  setSlowThresholdMs(value: number): void
  /**
   * Subscriber wiring lands in a later 0.6.x slice; the binding
   * accepts the call so callers can wire a callback against the
   * public surface without a runtime error.
   */
  attachSubscriber(callback: unknown, options?: AttachSubscriberOptions | undefined | null): void
}
