use std::sync::Arc;

use crate::dependency_closure;
use crate::filter::{
    append_node_eligibility_sql, validate_filter_attributes_on_snapshot, SearchFilter,
    SnapshotFilterError,
};
use crate::frozen_read::{self, FrozenReadError};
use crate::read::NodeRecord;
use crate::reader_transaction::begin_attributed_reader_tx;
use crate::search_types::{SearchHit, SoftFallbackBranch};
#[cfg(feature = "tc5-benchmark")]
use crate::tc5_benchmark;
use crate::temporal::{edge_validity_sql_for_view, BoundaryCrossing, FrozenView, ReadView};
use crate::wal_attribution::WalAttributionCollector;
use rusqlite::{params, Connection, OptionalExtension};

use super::types::TraversalDirection;

pub(crate) enum SearchExpandHandlerError {
    Sqlite(rusqlite::Error),
    FrozenRead(FrozenReadError),
    InvalidFilter(String),
}

impl From<rusqlite::Error> for SearchExpandHandlerError {
    fn from(error: rusqlite::Error) -> Self {
        Self::Sqlite(error)
    }
}

impl From<SnapshotFilterError> for SearchExpandHandlerError {
    fn from(error: SnapshotFilterError) -> Self {
        match error {
            SnapshotFilterError::Sqlite(error) => Self::Sqlite(error),
            SnapshotFilterError::InvalidFilter(reason) => Self::InvalidFilter(reason),
        }
    }
}

/// Slice 20 (G6) — result of [`Engine::search_expand`]: initial search hits
/// plus nodes reached by bounded BFS expansion that are not already in the
/// search hit set.
#[derive(Clone, Debug)]
pub struct SearchExpandResult {
    /// Original RRF-scored search results (G1+G9 hybrid).
    pub search_hits: Vec<SearchHit>,
    /// Nodes reached by graph traversal but NOT already in `search_hits`.
    /// Each entry is `(node, hop_count)` where `hop_count` is the BFS depth
    /// from the nearest search hit that reached this node.
    pub expanded: Vec<(NodeRecord, u32)>,
    /// Deduplicated union of all logical_ids (search hits first, then expanded).
    pub all_logical_ids: Vec<String>,
}

// ---------------------------------------------------------------------------
// Slice 20 (G5/G6) — BFS graph-traversal helpers
// ---------------------------------------------------------------------------

/// Hard cap on the number of nodes returned by a single `graph_neighbors` call.
/// Ported from v0.5.6 `MAX_TRAVERSAL_DEPTH` (applied as a LIMIT on the CTE and
/// the final SELECT). Defense-in-depth against unbounded traversal.
const GRAPH_NEIGHBORS_HARD_CAP: usize = 50;

/// Build the BFS CTE SQL for the given `direction`, under `view`.
///
/// Parameters (positional):
///   `?1` — root `logical_id`
///   `?2` — max_depth (`u32`, SDK-facing depth ceiling ≤ 3)
///   `?3` — R-20-NV node-validity instant (`:now` seam), emitted at EVERY node
///          position; omitted entirely when the view relaxes validity.
///
/// `LIMIT {GRAPH_NEIGHBORS_HARD_CAP}` appears on both the CTE and the final SELECT.
///
/// # Why one template instead of three
///
/// The three directions previously carried three hand-maintained copies of the
/// CTE, each repeating the node predicate at THREE positions (anchor, recursive
/// join, final projection) — nine hand-written copies in total. R-20-RV requires
/// a relax flag to apply at every one of them, and nine copies is exactly the
/// shape in which "it works on `Outgoing` but silently not on `Both`" hides. The
/// directions are folded into ONE template parameterised by the two things that
/// actually differ (the edge join condition and the traversed-to expression), so
/// `view.node_sql(...)` is written once per position and applying to all three
/// directions is structural rather than a thing to remember.
///
/// **TC-33: the `canonical_edges` temporal filter is now parameterised too.** It
/// was `datetime(e.t_invalid) > datetime('now')` inline, deliberately left alone
/// while edge validity was ISO-8601 TEXT. Edge timestamps are INTEGER epoch
/// seconds now, so the predicate is generated by [`edge_validity_sql`] and binds
/// the frozen instant at `?4` — no inline clock remains in this template.
fn build_bfs_sql(direction: TraversalDirection, view: &ReadView) -> String {
    let cap = GRAPH_NEIGHBORS_HARD_CAP;
    // cte_cap: the SQLite CTE LIMIT counts path-rows, not distinct nodes. In a
    // multigraph (multiple parallel edges between the same pair of nodes), the CTE
    // can contain duplicate-target rows before the final SELECT DISTINCT. A cap of
    // cap+1 would be exhausted by ~50 parallel edges to the same node, preventing
    // other neighbors from being discovered. Use cap*cap as a generous safety
    // ceiling that still bounds CTE growth for any realistic graph while allowing
    // the final SELECT LIMIT cap to be the authoritative distinct-node cap.
    let cte_cap = cap * cap;
    // Cycle guard uses char(30) (ASCII Record Separator, 0x1E) as delimiter instead
    // of comma, so logical_ids containing commas are handled correctly. char(30) is
    // a non-printable control character that callers cannot place in logical_id values
    // via normal text input.
    //
    // `?3` is the node-validity instant. Positional (not named), so the repeated
    // occurrences across the three node positions all bind the SAME value once.
    const NOW_IDX: usize = 3;
    // TC-33: `?4` is the EDGE-validity instant, bound separately because the node
    // instant is `Option` (relaxed by `include_out_of_window`) while edge recency
    // is always applied.
    const EDGE_NOW_IDX: usize = 4;

    // The ONLY two things that differ between directions.
    let (edge_join, target_expr) = match direction {
        TraversalDirection::Outgoing => ("e.from_id = t.logical_id", "e.to_id"),
        TraversalDirection::Incoming => ("e.to_id = t.logical_id", "e.from_id"),
        TraversalDirection::Both => (
            "(e.from_id = t.logical_id OR e.to_id = t.logical_id)",
            "CASE WHEN e.from_id = t.logical_id THEN e.to_id ELSE e.from_id END",
        ),
    };

    // Position 1 (anchor), position 2 (recursive join), position 3 (final
    // projection) — the view is applied at all three, for every direction.
    let anchor_node = view.node_sql("n", NOW_IDX);
    let next_node = view.node_sql("next_n", NOW_IDX);
    let projection_node = view.node_sql("n", NOW_IDX);
    let edge_valid = edge_validity_sql_for_view("e", EDGE_NOW_IDX, view);

    format!(
        "WITH RECURSIVE
  traversal(logical_id, depth, visited) AS (
    SELECT n.logical_id, 0, char(30) || n.logical_id || char(30)
    FROM canonical_nodes n
    WHERE n.logical_id = ?1{anchor_node}
    UNION ALL
    SELECT {target_expr}, t.depth + 1, t.visited || {target_expr} || char(30)
    FROM traversal t
    JOIN canonical_edges e ON {edge_join}
    JOIN canonical_nodes next_n ON next_n.logical_id = {target_expr}{next_node}
    WHERE t.depth < ?2
      AND e.superseded_at IS NULL{edge_valid}
      AND instr(t.visited, char(30) || {target_expr} || char(30)) = 0
    LIMIT {cte_cap}
  )
SELECT DISTINCT n.logical_id, n.kind, n.body, n.write_cursor
FROM traversal tr
JOIN canonical_nodes n ON n.logical_id = tr.logical_id
WHERE tr.logical_id != ?1{projection_node}
LIMIT {cap}"
    )
}

/// Build the BFS CTE SQL for `search_expand` — identical to `build_bfs_sql`
/// but the final SELECT uses `GROUP BY` + `MIN(tr.depth)` so that each
/// expanded node carries its actual BFS distance from the root.
///
/// Returns 5 columns: logical_id, kind, body, write_cursor, min_depth.
fn build_bfs_with_depth_sql(
    view: FrozenView,
    filter: Option<&SearchFilter>,
) -> (String, Vec<rusqlite::types::Value>) {
    let cap = GRAPH_NEIGHBORS_HARD_CAP;
    let cte_cap = cap * cap; // same multigraph-safe headroom as build_bfs_sql
                             // TC-33: `?1` anchor, `?2` depth ⇒ the edge `:now` binds at `?3`. This is a
                             // SECOND, separate BFS template — the edge-validity predicate has to be
                             // re-grounded here too or `search_expand` silently keeps the old semantics.
    let anchor_node = view.node_sql("n", 3);
    let next_node = view.node_sql("next_n", 3);
    let projection_node = view.node_sql("n", 3);
    let edge_valid = edge_validity_sql_for_view("e", 3, &view.view);
    // Reserve ?1 (root), ?2 (depth), and ?3 (the frozen validity instant).
    // Eligibility is emitted independently at each node position because a
    // recursive frontier must never admit an ineligible node and the final
    // cap must count only eligible rows.
    let mut params = vec![rusqlite::types::Value::Null; 3];
    let anchor_eligibility = append_node_eligibility_sql(filter, "n", &mut params);
    let next_eligibility = append_node_eligibility_sql(filter, "next_n", &mut params);
    let projection_eligibility = append_node_eligibility_sql(filter, "n", &mut params);
    let sql = format!(
        "WITH RECURSIVE
  traversal(logical_id, depth, visited) AS (
    SELECT n.logical_id, 0, char(30) || n.logical_id || char(30)
    FROM canonical_nodes n
    WHERE n.logical_id = ?1 AND ?3 IS NOT NULL{anchor_node}{anchor_eligibility}
    UNION ALL
    SELECT
      CASE WHEN e.from_id = t.logical_id THEN e.to_id ELSE e.from_id END,
      t.depth + 1,
      t.visited || CASE WHEN e.from_id = t.logical_id THEN e.to_id ELSE e.from_id END || char(30)
    FROM traversal t
    JOIN canonical_edges e ON (e.from_id = t.logical_id OR e.to_id = t.logical_id)
    JOIN canonical_nodes next_n
      ON next_n.logical_id = CASE WHEN e.from_id = t.logical_id THEN e.to_id ELSE e.from_id END
      {next_node}{next_eligibility}
    WHERE t.depth < ?2
      AND e.superseded_at IS NULL{edge_valid}
      AND instr(t.visited,
            char(30) || CASE WHEN e.from_id = t.logical_id THEN e.to_id ELSE e.from_id END || char(30)) = 0
    LIMIT {cte_cap}
  )
SELECT n.logical_id, n.kind, n.body, n.write_cursor, MIN(tr.depth) AS min_depth
FROM traversal tr
JOIN canonical_nodes n ON n.logical_id = tr.logical_id
WHERE tr.logical_id != ?1{projection_node}{projection_eligibility}
GROUP BY n.logical_id
LIMIT {cap}"
    );
    (sql, params)
}

/// 0.8.20 Slice 10b (R-20-NV) — the validity-boundary hook, on the DEFERRED
/// reader transaction.
///
/// Reports nodes whose `valid_from` and/or `valid_until` falls in the half-open
/// interval `(since, upper]`. Both bounds are BOUND parameters (`?1`, `?2`) —
/// the node-validity path never inlines `datetime('now')`.
///
/// The view's EXISTENCE conjunct applies (default: current + active rows only);
/// its VALIDITY conjunct deliberately does not, because the question is "did
/// this window cross a boundary", not "is this row valid now".
pub(crate) fn crossed_boundary_since_in_tx(
    reader: &mut Connection,
    since: i64,
    view: &ReadView,
    attribution: &Arc<WalAttributionCollector>,
    worker_idx: usize,
) -> rusqlite::Result<Vec<BoundaryCrossing>> {
    // `now_param()` is None exactly when the view relaxes validity, which here
    // means "no upper bound on the interval".
    let upper = view.now_param().unwrap_or(i64::MAX);
    let existence = view.existence_sql("canonical_nodes");
    let eligibility = dependency_closure::read_eligibility_sql(
        "canonical_nodes",
        view.include_superseded,
        view.include_inactive,
        view.include_out_of_window,
        2,
    );
    // `1 = 1` keeps the leading ` AND ` of `existence_sql` well-formed even when
    // every existence flag is relaxed and the conjunct is empty.
    let sql = format!(
        "SELECT logical_id, kind, body, write_cursor, valid_from, valid_until \
         FROM canonical_nodes \
         WHERE 1 = 1{existence}{eligibility} \
           AND logical_id IS NOT NULL \
           AND ( (valid_from IS NOT NULL AND valid_from > ?1 AND valid_from <= ?2) \
              OR (valid_until IS NOT NULL AND valid_until > ?1 AND valid_until <= ?2) ) \
         ORDER BY write_cursor"
    );
    let tx = begin_attributed_reader_tx(reader, attribution, worker_idx)?;
    let mut statement = tx.prepare(&sql)?;
    let rows = statement.query_map(params![since, upper], |row| {
        let valid_from: Option<i64> = row.get(4)?;
        let valid_until: Option<i64> = row.get(5)?;
        Ok(BoundaryCrossing {
            node: NodeRecord {
                logical_id: row.get(0)?,
                kind: row.get(1)?,
                body: row.get(2)?,
                write_cursor: row.get::<_, i64>(3)? as u64,
            },
            became_valid_at: valid_from.filter(|t| *t > since && *t <= upper),
            became_invalid_at: valid_until.filter(|t| *t > since && *t <= upper),
        })
    })?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row?);
    }
    Ok(out)
}

/// Slice 20 (G5) — execute a bounded BFS on the DEFERRED reader transaction.
/// Called inside the reader worker loop.
pub(crate) fn graph_neighbors_in_tx(
    reader: &mut Connection,
    root_logical_id: &str,
    depth: u32,
    direction: TraversalDirection,
    view: &ReadView,
    attribution: &Arc<WalAttributionCollector>,
    worker_idx: usize,
) -> rusqlite::Result<Vec<NodeRecord>> {
    #[cfg(feature = "tc5-benchmark")]
    tc5_benchmark::record_graph_route();
    let sql = build_bfs_sql(direction, view);
    let tx = begin_attributed_reader_tx(reader, attribution, worker_idx)?;
    let depth_i64 = depth as i64;
    let mut statement = tx.prepare(&sql)?;
    // ?1 root, ?2 depth, ?3 = the NODE validity instant, ?4 = the EDGE validity
    // instant (TC-33).
    //
    // ?3 is bound UNCONDITIONALLY even when the view relaxes node validity and
    // `build_bfs_sql` emitted no `?3`: the template still references ?4, so
    // SQLite's parameter count is 4 and the positions must not shift. Binding an
    // index the SQL never reads is harmless; letting ?4's value slide into ?3
    // would silently compare edge times against a placeholder.
    let frozen = (*view).freeze();
    let binds: Vec<rusqlite::types::Value> = vec![
        rusqlite::types::Value::Text(root_logical_id.to_string()),
        rusqlite::types::Value::Integer(depth_i64),
        rusqlite::types::Value::Integer(frozen.now_param().unwrap_or_default()),
        rusqlite::types::Value::Integer(frozen.edge_now()),
    ];
    let rows = statement.query_map(rusqlite::params_from_iter(binds.iter()), |row| {
        Ok(NodeRecord {
            logical_id: row.get(0)?,
            kind: row.get(1)?,
            body: row.get(2)?,
            write_cursor: row.get::<_, i64>(3)? as u64,
        })
    })?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row?);
    }
    Ok(out)
}

/// Slice 20 (G6) — resolve search hit `write_cursor`s to `logical_id`s, run
/// BFS for each root, and merge into a [`SearchExpandResult`]. Called inside
/// the reader worker loop on the DEFERRED reader transaction.
#[allow(clippy::too_many_arguments)]
pub(crate) fn search_expand_in_tx(
    reader: &mut Connection,
    search_hits: &[SearchHit],
    depth: u32,
    view: ReadView,
    filter: Option<&SearchFilter>,
    frozen_binding: Option<&frozen_read::FrozenReadBinding>,
    attribution: &Arc<WalAttributionCollector>,
    worker_idx: usize,
) -> Result<SearchExpandResult, SearchExpandHandlerError> {
    let tx = begin_attributed_reader_tx(reader, attribution, worker_idx)?;
    if let Some(expected) = frozen_binding {
        frozen_read::validate_snapshot(&tx, expected)
            .map_err(SearchExpandHandlerError::FrozenRead)?;
    }
    if let Some(filter) = filter {
        validate_filter_attributes_on_snapshot(&tx, filter)?;
    }
    let result = search_expand_on_snapshot(&tx, search_hits, depth, view.freeze(), filter)?;
    tx.commit()?;
    Ok(result)
}

/// Resolve and expand search hits on an already-pinned reader snapshot.
pub(crate) fn search_expand_on_snapshot(
    tx: &Connection,
    search_hits: &[SearchHit],
    depth: u32,
    frozen: FrozenView,
    filter: Option<&SearchFilter>,
) -> Result<SearchExpandResult, SearchExpandHandlerError> {
    // Step 1: resolve write_cursor → logical_id for each search hit.
    // Possible outcomes per hit:
    //   - None: no matching write_cursor in canonical_nodes (superseded) → drop.
    //   - Some(""):  row exists but logical_id IS NULL (anonymous node) or TextEdge hit
    //                → keep as valid search result, skip BFS expansion (empty sentinel).
    //   - Some(lid): active named node → keep; use as BFS root.
    let mut hit_logical_ids: Vec<Option<String>> = Vec::with_capacity(search_hits.len());
    {
        let node_predicate = frozen.node_sql("canonical_nodes", 2);
        let mut node_stmt = tx.prepare(&format!(
            "SELECT logical_id FROM canonical_nodes
             WHERE write_cursor = ?1{node_predicate}
             LIMIT 1"
        ))?;
        let edge_predicate = edge_validity_sql_for_view("canonical_edges", 2, &frozen.view);
        let mut edge_stmt = tx.prepare(&format!(
            "SELECT 1 FROM canonical_edges
             WHERE write_cursor = ?1 AND superseded_at IS NULL{edge_predicate}
             LIMIT 1"
        ))?;
        for hit in search_hits {
            if hit.branch == SoftFallbackBranch::TextEdge {
                // Edge-body hit: verify the edge row is still active in THIS snapshot.
                // Stale edge hits (superseded between search and expansion) are dropped.
                let cursor_i64 = hit.write_cursor as i64;
                let active: Option<i32> = edge_stmt
                    .query_row(params![cursor_i64, frozen.edge_now()], |row| row.get(0))
                    .optional()?;
                if active.is_some() {
                    hit_logical_ids.push(Some(String::new())); // sentinel: keep hit, skip BFS
                } else {
                    hit_logical_ids.push(None); // superseded edge: drop
                }
            } else {
                let cursor_i64 = hit.write_cursor as i64;
                // Returns Option<Option<String>>:
                //   None         → no row → superseded
                //   Some(None)   → row with NULL logical_id → anonymous node
                //   Some(Some(s)) → active named node
                let mut bind_values = vec![rusqlite::types::Value::Integer(cursor_i64)];
                if let Some(now) = frozen.now_param() {
                    bind_values.push(rusqlite::types::Value::Integer(now));
                }
                let resolved = node_stmt
                    .query_row(rusqlite::params_from_iter(bind_values.iter()), |row| {
                        row.get::<_, Option<String>>(0)
                    })
                    .optional()?;
                match resolved {
                    None => hit_logical_ids.push(None), // superseded: drop
                    Some(None) => hit_logical_ids.push(Some(String::new())), // anon: keep, skip BFS
                    Some(Some(lid)) => hit_logical_ids.push(Some(lid)), // named: keep + BFS root
                }
            }
        }
    }

    // Build a set of logical_ids present in the search hits (for deduplication).
    // Empty-string sentinels (TextEdge hits) are excluded — they are not real node ids.
    let hit_id_set: std::collections::HashSet<String> =
        hit_logical_ids.iter().filter_map(|id| id.clone()).filter(|s| !s.is_empty()).collect();

    // Step 2: for each root logical_id, run the BFS and collect expanded nodes.
    // A node already in `hit_id_set` is NOT added to `expanded`.
    // Use the depth-aware variant so each node reports its actual BFS distance.
    let (bfs_sql, bfs_parameter_template) = build_bfs_with_depth_sql(frozen, filter);
    let depth_i64 = depth as i64;
    // nearest_hop: for each expanded logical_id track the minimum hop count
    // seen across ALL search-hit roots. A node reachable from multiple roots
    // at different depths must report the shortest distance (nearest root).
    let mut nearest_hop: std::collections::HashMap<String, (NodeRecord, u32)> =
        std::collections::HashMap::new();

    if depth > 0 {
        let mut bfs_stmt = tx.prepare(&bfs_sql)?;
        // `?3` is the one frozen node/edge validity instant. Every root uses
        // the same authenticated view and eligibility envelope.
        let edge_now = frozen.edge_now();
        for root_id in hit_logical_ids.iter().flatten().filter(|s| !s.is_empty()) {
            let mut binds = bfs_parameter_template.clone();
            binds[0] = rusqlite::types::Value::Text(root_id.clone());
            binds[1] = rusqlite::types::Value::Integer(depth_i64);
            binds[2] = rusqlite::types::Value::Integer(edge_now);
            let neighbor_rows =
                bfs_stmt.query_map(rusqlite::params_from_iter(binds.iter()), |row| {
                    let node = NodeRecord {
                        logical_id: row.get(0)?,
                        kind: row.get(1)?,
                        body: row.get(2)?,
                        write_cursor: row.get::<_, i64>(3)? as u64,
                    };
                    let min_depth: i64 = row.get(4)?;
                    Ok((node, min_depth as u32))
                })?;
            for row_result in neighbor_rows {
                let (node, hop_count) = row_result?;
                if hit_id_set.contains(&node.logical_id) {
                    // Already a search hit — skip (search score takes priority).
                    continue;
                }
                nearest_hop
                    .entry(node.logical_id.clone())
                    .and_modify(|(_, prev_hop)| {
                        if hop_count < *prev_hop {
                            *prev_hop = hop_count;
                        }
                    })
                    .or_insert((node, hop_count));
            }
        }
    }

    // Materialize expanded in insertion order (deterministic for tests).
    let mut expanded: Vec<(NodeRecord, u32)> = nearest_hop.into_values().collect();
    expanded.sort_by(|(a, _), (b, _)| a.logical_id.cmp(&b.logical_id));

    // Filter search_hits to only include those whose write_cursor resolved to an
    // active logical_id in THIS snapshot. Hits that were superseded between the
    // search phase and the expansion phase (the two-snapshot window) are dropped
    // rather than returned with stale data.
    let resolved_hits: Vec<SearchHit> = search_hits
        .iter()
        .zip(hit_logical_ids.iter())
        .filter_map(|(hit, lid)| lid.as_ref().map(|_| hit.clone()))
        .collect();

    // Build `all_logical_ids` = resolved search-hit logical_ids + expanded node ids.
    // Empty-string sentinels (TextEdge hits) are excluded — they are not real node ids.
    let mut all_logical_ids: Vec<String> =
        hit_logical_ids.into_iter().flatten().filter(|s| !s.is_empty()).collect();
    for (node, _) in &expanded {
        if !all_logical_ids.contains(&node.logical_id) {
            all_logical_ids.push(node.logical_id.clone());
        }
    }

    Ok(SearchExpandResult { search_hits: resolved_hits, expanded, all_logical_ids })
}

/// Slice 20 test seam — run `EXPLAIN QUERY PLAN` on the BFS CTE SQL and return
/// the plan `detail` column (column index 3) for each row. Used by
/// `explain_plan_uses_indexes` to assert index usage.
pub(crate) fn explain_graph_neighbors_in_tx(
    reader: &mut Connection,
    root_logical_id: &str,
    depth: u32,
    direction: TraversalDirection,
    attribution: &Arc<WalAttributionCollector>,
    worker_idx: usize,
) -> rusqlite::Result<Vec<String>> {
    // The EXPLAIN index-usage gate measures the DEFAULT (strict) read path.
    let view = ReadView::default();
    let bfs_sql = build_bfs_sql(direction, &view);
    let explain_sql = format!("EXPLAIN QUERY PLAN {bfs_sql}");
    let tx = begin_attributed_reader_tx(reader, attribution, worker_idx)?;
    let depth_i64 = depth as i64;
    let mut statement = tx.prepare(&explain_sql)?;
    // EXPLAIN QUERY PLAN returns rows: (id, parent, notused, detail).
    // We collect the `detail` column (index 3).
    // The strict view emits `?3` (the node-validity instant) at every node
    // position; TC-33 adds `?4`, the edge-validity instant.
    let frozen = view.freeze();
    let now = frozen.now_param().expect("the strict view always binds a validity instant");
    let rows = statement
        .query_map(params![root_logical_id, depth_i64, now, frozen.edge_now()], |row| {
            row.get::<_, String>(3)
        })?;
    let mut out = Vec::new();
    for row in rows {
        out.push(row?);
    }
    Ok(out)
}
