"""FathomDB Python SDK public surface.

Top-level five-verb surface and exception hierarchy owned by
`dev/interfaces/python.md` + `dev/design/errors.md`. The package delegates
to the native PyO3 extension `fathomdb._fathomdb` which binds to
`fathomdb-engine`.
"""

from __future__ import annotations

# AC80-25 / D-80.6-3 — FIRST, before the native extension is loaded: refuse to
# run when two FathomDB distributions (e.g. the generic and the Tegra wheels)
# are installed into one environment. They ship the same top-level `fathomdb`
# import package, so the second install silently shadows the first's native
# extension. No pip/PEP-621 metadata can express that conflict, so this
# import-time check is the enforcement; see `fathomdb/_coinstall.py`.
from fathomdb import _coinstall  # noqa: F401 — import-time co-installation guard
from fathomdb import _fathomdb as _native  # noqa: F401 — load native extension
from fathomdb import admin, errors, graph, read
from fathomdb._fathomdb import ConsolidateReceipt
from fathomdb._fathomdb import IngestWithExtractorReceipt
from fathomdb._fathomdb import embed_batch_cls
from fathomdb._fathomdb import rerank
from fathomdb.config import EngineConfig
from fathomdb.engine import Engine
from fathomdb.errors import (
    DependencyTraceError,
    EvidenceError,
    FrozenReadError,
    GraphExpansionError,
    PageError,
)
from fathomdb.filter import Filter
from fathomdb.types import (
    ActuationBatchV1,
    ActuationOperationV1,
    ActuationReceiptV1,
    CounterSnapshot,
    ClosureLookupV1,
    ClosureProofV1,
    ClosureStatusV1,
    CanonicalHash,
    CanonicalWriteProvenanceV1,
    CudaDeviceInfo,
    CudaVisibleDevice,
    DenseReadiness,
    DeviceResolution,
    DerivedWriteProvenanceV1,
    DependencyDerivedLookupV1,
    DependencyListV1,
    DependencySourceLookupV1,
    DependencyTraceRequestV1,
    DependencyTraceEdgeV1,
    DependencyTraceNodeV1,
    DependencyTraceResultV1,
    EmbeddingOperation,
    EmbeddingReadiness,
    EmbeddingReadinessState,
    EffectiveEmbedDevice,
    EvidenceArtifactLifecycleV1,
    EvidenceContributionV1,
    EvidenceGraphOriginV1,
    EvidenceProjectionOriginV1,
    EvidenceResolveRequestV1,
    EvidenceSearchRequestV1,
    EvidenceSearchResultV1,
    EvidenceSidecarEntryV1,
    ExpandedNode,
    Explanation,
    FrozenReadContextV1,
    GpuAllocationWitness,
    CurrentGraphReadContextV1,
    FrozenGraphReadContextV1,
    GraphExpandRequestV1,
    GraphExpandResultV1,
    GraphEvidenceArtifactV1,
    GraphEvidenceResolveRequestV1,
    GraphEvidenceSidecarEntryV1,
    GraphEvidenceSidecarV1,
    GraphExpansionDegradationCodeV1,
    GraphExpansionExplanationV1,
    GraphExplicitSeedV1,
    GraphOriginV1,
    GraphProjectionOriginV1,
    GraphProjectionReadinessV1,
    GraphQuerySeedV1,
    GraphReadContextV1,
    GraphReadModeV1,
    GraphSeedSourceV1,
    GraphSeedV1,
    GraphTargetExplanationV1,
    GraphTargetV1,
    ResolvedGraphEvidenceV1,
    IdSpace,
    NodeRecord,
    OpStoreRow,
    OperationalStateRecordV1,
    PageCursor,
    PageRequestV1,
    PageV1,
    PerHitExplain,
    ProjectionDelta,
    MutationProjectionStatusRequestV1,
    MutationProjectionStatusV1,
    ProjectionGenerationOriginV1,
    ProjectionGenerationStatusV1,
    ProjectionReadinessV1,
    ProjectionRuntimeStateV1,
    ProjectionRole,
    ProjectionRuntimeStatus,
    ProjectionRuntimeStatusEntry,
    ProjectionRuntimeUnavailabilityReason,
    ProjectionSpec,
    ProjectionStatusDenseReadiness,
    QueryTrace,
    ReadContextV1,
    ReadView,
    ResolvedEvidenceV1,
    ResolvedGraphSeedV1,
    SearchExpandResult,
    SearchFilter,
    SearchHit,
    SearchResult,
    SourceDependencyRegistrationV1,
    SourceDependencyV1,
    SourceLocator,
    Utf8BytesSourceLocator,
    WholeBodySourceLocator,
    SoftFallback,
    SoftFallbackBranch,
    StructuralInclusionV1,
    TraversalDirection,
    TraceNodeLifecycleV1,
    TraceReadBoundaryV1,
    WriteReceipt,
    WriteProvenanceV1,
)

__all__ = [
    "ActuationBatchV1",
    "ActuationOperationV1",
    "ActuationReceiptV1",
    "ConsolidateReceipt",
    "CanonicalHash",
    "CanonicalWriteProvenanceV1",
    "CounterSnapshot",
    "ClosureLookupV1",
    "ClosureProofV1",
    "ClosureStatusV1",
    "CudaDeviceInfo",
    "CudaVisibleDevice",
    "DenseReadiness",
    "DeviceResolution",
    "DerivedWriteProvenanceV1",
    "DependencyDerivedLookupV1",
    "DependencyListV1",
    "DependencySourceLookupV1",
    "DependencyTraceError",
    "DependencyTraceRequestV1",
    "DependencyTraceEdgeV1",
    "DependencyTraceNodeV1",
    "DependencyTraceResultV1",
    "EmbeddingOperation",
    "EmbeddingReadiness",
    "EmbeddingReadinessState",
    "EffectiveEmbedDevice",
    "EvidenceArtifactLifecycleV1",
    "EvidenceContributionV1",
    "EvidenceError",
    "EvidenceGraphOriginV1",
    "EvidenceProjectionOriginV1",
    "EvidenceResolveRequestV1",
    "EvidenceSearchRequestV1",
    "EvidenceSearchResultV1",
    "EvidenceSidecarEntryV1",
    "Engine",
    "EngineConfig",
    "Filter",
    "IngestWithExtractorReceipt",
    "ExpandedNode",
    "Explanation",
    "FrozenReadContextV1",
    "FrozenReadError",
    "GpuAllocationWitness",
    "CurrentGraphReadContextV1",
    "FrozenGraphReadContextV1",
    "GraphExpandRequestV1",
    "GraphExpandResultV1",
    "GraphEvidenceArtifactV1",
    "GraphEvidenceResolveRequestV1",
    "GraphEvidenceSidecarEntryV1",
    "GraphEvidenceSidecarV1",
    "GraphExpansionDegradationCodeV1",
    "GraphExpansionError",
    "GraphExpansionExplanationV1",
    "GraphExplicitSeedV1",
    "GraphOriginV1",
    "GraphProjectionOriginV1",
    "GraphProjectionReadinessV1",
    "GraphQuerySeedV1",
    "GraphReadContextV1",
    "GraphReadModeV1",
    "GraphSeedSourceV1",
    "GraphSeedV1",
    "GraphTargetExplanationV1",
    "GraphTargetV1",
    "ResolvedGraphEvidenceV1",
    "IdSpace",
    "NodeRecord",
    "OpStoreRow",
    "OperationalStateRecordV1",
    "PageCursor",
    "PageError",
    "PageRequestV1",
    "PageV1",
    "PerHitExplain",
    "ProjectionDelta",
    "MutationProjectionStatusRequestV1",
    "MutationProjectionStatusV1",
    "ProjectionGenerationOriginV1",
    "ProjectionGenerationStatusV1",
    "ProjectionReadinessV1",
    "ProjectionRuntimeStateV1",
    "ProjectionRole",
    "ProjectionRuntimeStatus",
    "ProjectionRuntimeStatusEntry",
    "ProjectionRuntimeUnavailabilityReason",
    "ProjectionSpec",
    "ProjectionStatusDenseReadiness",
    "QueryTrace",
    "ReadContextV1",
    "ReadView",
    "ResolvedEvidenceV1",
    "ResolvedGraphSeedV1",
    "SearchExpandResult",
    "SearchFilter",
    "SearchHit",
    "SearchResult",
    "SourceDependencyRegistrationV1",
    "SourceDependencyV1",
    "SourceLocator",
    "Utf8BytesSourceLocator",
    "WholeBodySourceLocator",
    "SoftFallback",
    "SoftFallbackBranch",
    "StructuralInclusionV1",
    "TraversalDirection",
    "TraceNodeLifecycleV1",
    "TraceReadBoundaryV1",
    "WriteReceipt",
    "WriteProvenanceV1",
    "__version__",
    "admin",
    "embed_batch_cls",
    "errors",
    "graph",
    "read",
    "rerank",
]
__version__ = "0.8.25"
