#!/usr/bin/env python3
"""Fast-tier self-tests for the 0.8.27 hidden-surface oracle.

Every rustdoc input is a committed, canonicalized fixture generated by
`scripts/tests/fixtures/hidden-surface/regenerate.sh`; these tests never need
the pinned nightly toolchain or the network.
"""

from __future__ import annotations

import copy
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile
from types import ModuleType, SimpleNamespace
from typing import Any, Callable
from unittest import mock


ROOT = Path(__file__).resolve().parents[2]
TOOL = ROOT / "dev" / "tools" / "hidden_surface.py"
FIXTURES = ROOT / "scripts" / "tests" / "fixtures" / "hidden-surface"
JSON = FIXTURES / "json"
SHA = "1" * 40
OTHER_SHA = "2" * 40


def load_tool() -> ModuleType:
    spec = importlib.util.spec_from_file_location("hidden_surface", TOOL)
    if spec is None or spec.loader is None:
        raise AssertionError(f"cannot load hidden-surface tool: {TOOL}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def doc(name: str) -> dict[str, Any]:
    return json.loads((JSON / f"{name}.json").read_text())


def by_path(records: list[Any]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for record in records:
        assert record.path not in result, f"duplicate path {record.path}"
        result[record.path] = record
    return result


def sig(record: Any) -> dict[str, Any]:
    return json.loads(record.signature)


def entry_keys(entries: list[dict[str, str]]) -> set[tuple[str, str, str]]:
    return {(e["path"], e["kind"], e["signature"]) for e in entries}


def expect_error(tool: ModuleType, call: Callable[[], Any], fragment: str) -> None:
    try:
        call()
    except tool.HiddenSurfaceError as exc:
        assert fragment in str(exc), (fragment, str(exc))
        return
    raise AssertionError(f"expected HiddenSurfaceError containing {fragment!r}")


OFFSET = 100_000
ID_LIST_KEYS = {"items", "impls", "variants", "fields", "implementations", "tuple"}


def renumber(value: Any, key: str | None = None) -> Any:
    """Consistently shift every rustdoc id, including map keys and id lists."""

    if isinstance(value, dict):
        shifted: dict[str, Any] = {}
        for child_key, child in value.items():
            if child_key in ("id", "root") and isinstance(child, int):
                shifted[child_key] = child + OFFSET
            elif child_key == "links" and isinstance(child, dict):
                shifted[child_key] = {k: v + OFFSET for k, v in child.items()}
            else:
                shifted[child_key] = renumber(child, child_key)
        return shifted
    if isinstance(value, list):
        if key in ID_LIST_KEYS and all(
            isinstance(item, int) or item is None for item in value
        ):
            return [item + OFFSET if isinstance(item, int) else item for item in value]
        return [renumber(item, key) for item in value]
    return value


def renumbered(document: dict[str, Any]) -> dict[str, Any]:
    result = renumber(document)
    result["index"] = {str(int(k) + OFFSET): v for k, v in result["index"].items()}
    result["paths"] = {str(int(k) + OFFSET): v for k, v in result["paths"].items()}
    return result


def manifest(
    tool: ModuleType, rows: dict[str, list[dict[str, str]]], **extra: Any
) -> dict[str, Any]:
    metadata = {
        "schema": tool.SCHEMA,
        "capture_source_sha": SHA,
        "source_modified": False,
        "tools": {
            "rust-toolchain": tool.PINNED_NIGHTLY,
            "rustc": "rustc 1.97.0-nightly",
        },
        "rustdoc_format_version": tool.FORMAT_VERSION,
        "target": "x86_64-unknown-linux-gnu",
        "row_identities": [{"id": row_id} for row_id in sorted(rows)],
    }
    metadata.update(extra)
    return tool.build_manifest(metadata, rows)


def test_cfg_parser(tool: ModuleType) -> None:
    span = "src/lib.rs:1:7: 1:23 (#0)"
    parse = tool.parse_cfg_attr
    assert (
        parse(
            f'#[attr = CfgTrace([NameValue {{ name: "debug_assertions", value: None, span: {span} }}])]'
        )
        == "debug_assertions"
    )
    assert (
        parse(
            f'#[attr = CfgTrace([NameValue {{ name: "feature", value: Some("hooks"), span: {span} }}])]'
        )
        == 'feature = "hooks"'
    )
    assert (
        parse(
            f'#[attr = CfgTrace([Not(NameValue {{ name: "feature", value: Some("hooks"), span: {span} }}, {span})])]'
        )
        == 'not(feature = "hooks")'
    )
    # any/all operands are sorted into canonical order.
    assert (
        parse(
            "#[attr = CfgTrace([Any(["
            f'NameValue {{ name: "test", value: None, span: {span} }}, '
            f'NameValue {{ name: "debug_assertions", value: None, span: {span} }}, '
            f'NameValue {{ name: "feature", value: Some("test-hooks"), span: {span} }}'
            f"], {span})])]"
        )
        == 'any(debug_assertions, feature = "test-hooks", test)'
    )
    assert (
        parse(
            "#[attr = CfgTrace([All(["
            f'NameValue {{ name: "debug_assertions", value: None, span: {span} }}, '
            f'Not(NameValue {{ name: "feature", value: Some("hooks"), span: {span} }}, {span})'
            f"], {span})])]"
        )
        == 'all(debug_assertions, not(feature = "hooks"))'
    )
    # Two stacked predicates in one trace are a conjunction.
    assert (
        parse(
            "#[attr = CfgTrace(["
            f'NameValue {{ name: "test", value: None, span: {span} }}, '
            f'NameValue {{ name: "debug_assertions", value: None, span: {span} }}'
            "])]"
        )
        == "all(debug_assertions, test)"
    )
    for bad in (
        "#[attr = CfgTrace([Bool { value: true }])]",
        '#[attr = CfgTrace([NameValue { name: "x", value: None }])]',
        f'#[attr = CfgTrace([NameValue {{ name: "x", value: None, span: {span} }}]) trailing]',
        "#[cfg(debug_assertions)]",
    ):
        expect_error(tool, lambda bad=bad: parse(bad), "cfg")


def test_walk_hazards(tool: ModuleType) -> None:
    records = by_path(tool.walk(doc("base-default")))
    root = "hs_fixture"

    def p(name: str) -> Any:
        full = f"{root}::{name}"
        assert full in records, (full, sorted(records))
        return records[full]

    assert records[root].kind == "module"
    # Doc-hidden items at each site.
    # Signatures carry effective values only (owner ruling
    # hidden-surface-effective-and-inventory).
    for record in records.values():
        if record.kind not in ("external", "external-glob"):
            assert set(sig(record)) == {"visibility", "hidden", "cfg", "inner"}, (
                record.path
            )
    assert sig(p("hidden_fn_for_test"))["hidden"] is True
    assert sig(p("hidden_mod"))["hidden"] is True
    # An enclosing module's doc(hidden) folds into its members.
    assert sig(p("hidden_mod::inside"))["hidden"] is True
    assert sig(p("visible_mod::vis"))["hidden"] is False
    assert sig(p("plain_target"))["hidden"] is True
    assert sig(p("Thing::hidden_impl_method"))["hidden"] is True
    assert sig(p("Thing::get"))["hidden"] is False
    assert sig(p("Thing::peek_for_test"))["hidden"] is True
    assert sig(p("Thing::hidden_field"))["hidden"] is True
    assert sig(p("hook_for_test"))["hidden"] is True
    assert sig(p("make"))["hidden"] is False
    # Named and aliased re-exports carry the target's signature.
    assert p("make").kind == "function"
    assert sig(p("make"))["inner"] == sig(p("make_alias"))["inner"]
    assert '"path":"hs_fixture::Thing"' in p("make").signature
    # Glob expansion, with explicit items shadowing glob names.
    assert p("g1").kind == "function" and p("G2").kind == "struct"
    assert '"primitive":"u8"' in p("shadowed").signature
    all_records = tool.walk(doc("base-default"))
    assert [r.path for r in all_records].count(f"{root}::shadowed") == 1
    # Rustdoc drops the shadowed glob item from a private module, so add one
    # back: an explicit item must still win over a glob-imported namesake.
    shadowing = doc("base-default")
    index = shadowing["index"]
    explicit = next(v for v in index.values() if v["name"] == "shadowed")
    globbed = next(v for v in index.values() if v["name"] == "globbed")
    namesake = copy.deepcopy(explicit)
    namesake["id"] = 999_999
    namesake["inner"]["function"]["sig"]["output"] = {"primitive": "u16"}
    index["999999"] = namesake
    globbed["inner"]["module"]["items"].append(999_999)
    shadowed = [r for r in tool.walk(shadowing) if r.path == f"{root}::shadowed"]
    assert len(shadowed) == 1 and '"primitive":"u8"' in shadowed[0].signature
    assert '"primitive":"u16"' not in p("shadowed").signature
    external_glob = p("ext_glob::external-glob:core::hint")
    assert external_glob.kind == "external-glob"
    assert json.loads(external_glob.signature) == {
        "source": "core::hint",
        "cfg": None,
        "hidden": False,
    }
    # A cyclic module re-export is recorded once and not expanded.
    assert p("cyc::again").kind == "module"
    assert f"{root}::cyc::again::in_cyc" not in records
    assert p("vm_alias::vis").kind == "function"
    # Enum variants, struct fields, trait items.
    for variant in ("Unit", "Pair", "Named"):
        assert p(f"Shape::{variant}").kind == "variant"
    assert '"path":"hs_fixture::Thing"' in p("Shape::Pair").signature
    assert sig(p("Shape"))["inner"]["enum"]["variants"] == ["Named", "Pair", "Unit"]
    for item, kind in (
        ("LIMIT", "assoc_const"),
        ("Out", "assoc_type"),
        ("go", "function"),
        ("provided", "function"),
    ):
        assert p(f"Probe::{item}").kind == kind
    assert p("Tuple::0").kind == "struct_field" and p("Tuple::1").kind == "struct_field"
    assert f"{root}::Tuple::2" not in records
    assert f"{root}::Thing::y" not in records
    # Inherent impl items and trait impls with rendered generic arguments.
    assert p("Thing::get").kind == "function"
    for trait in (
        "core::clone::Clone",
        "core::convert::From<u32>",
        "core::convert::From<hs_fixture::Shape>",
        "hs_fixture::Probe",
    ):
        assert p(f"Thing::impl {trait}").kind == "impl"
    # Synthetic auto-trait impls and blanket instantiations are skipped.
    assert not any("impl core::marker::Send" in path for path in records)
    assert not any("impl core::convert::Into" in path for path in records)
    # The local blanket impl.
    assert p("impl hs_fixture::Marker for T").kind == "impl"
    # A constant whose expression names another constant keeps no `expr`.
    derived = p("DERIVED").signature
    assert "expr" not in derived and '"value"' in derived
    # Unreachable types are named by kind and name, with collision suffixes.
    tokens = p("takes_tokens").signature
    assert "private:struct:Token#1" in tokens and "private:struct:Token#2" in tokens
    assert "sealed" not in tokens
    # No rustdoc id or source location survives normalization.
    for record in records.values():
        assert '"id"' not in record.signature and '"span"' not in record.signature
        assert "src/" not in record.signature, record.path


def test_cfg_canonical_form(tool: ModuleType) -> None:
    """Effective cfg is signed in a semantic canonical form: the minimal
    sum-of-products over sorted atoms, lexicographically smallest on ties."""

    canonical = tool.canonical_cfg_text
    assert canonical(
        'all(any(feature = "test-hooks", test), feature = "test-hooks")'
    ) == ('feature = "test-hooks"')
    assert canonical('any(test, debug_assertions, feature = "test-hooks")') == (
        'any(debug_assertions, feature = "test-hooks", test)'
    )
    assert canonical("all(debug_assertions, debug_assertions)") == "debug_assertions"
    assert canonical("any(debug_assertions, not(debug_assertions))") is None
    assert canonical('all(not(feature = "hooks"), debug_assertions)') == (
        'all(debug_assertions, not(feature = "hooks"))'
    )
    assert canonical("not(not(test))") == "test"
    # Distributes to a minimal sum of products.
    assert canonical("all(any(a, b), any(a, c))") == "any(a, all(b, c))"
    assert canonical("all(a, not(a))") == "any()"
    too_many = "any(" + ", ".join(f"a{n}" for n in range(13)) + ")"
    expect_error(tool, lambda: canonical(too_many), "12")
    twelve = "any(" + ", ".join(f"a{n:02}" for n in range(12)) + ")"
    assert canonical(twelve) == twelve


def test_effective_values(tool: ModuleType) -> None:
    default = by_path(tool.walk(doc("base-default")))
    hooks = by_path(tool.walk(doc("base-hooks")))
    root = "hs_fixture::"

    def cfg(records: dict[str, Any], name: str) -> Any:
        return sig(records[root + name])["cfg"]

    assert cfg(default, "debug_only_for_test") == "debug_assertions"
    assert cfg(default, "without_hooks") == 'not(feature = "hooks")'
    assert cfg(default, "any_gate") == 'any(debug_assertions, feature = "hooks", test)'
    assert cfg(default, "all_gate") == 'all(debug_assertions, not(feature = "hooks"))'
    # Gated at the re-export only; at the impl block only; on the field only.
    assert cfg(default, "debug_reexported") == "debug_assertions"
    assert sig(default[root + "debug_reexported"])["hidden"] is True
    assert cfg(default, "Thing::debug_impl_method") == "debug_assertions"
    assert cfg(default, "Thing::impl hs_fixture::DebugOnlyTrait") == "debug_assertions"
    assert cfg(default, "Thing::debug_field") == "debug_assertions"
    assert cfg(default, "gate_both_probe") == "debug_assertions"
    assert cfg(default, "Thing::get") is None
    # Feature-gated hooks exist only in the feature row.
    assert root + "gated_hook" not in default
    assert cfg(hooks, "gated_hook") == 'feature = "hooks"'
    assert root + "reexport_gated_target" not in default
    assert cfg(hooks, "reexport_gated_target") == 'feature = "hooks"'
    assert root + "without_hooks" not in hooks and root + "all_gate" not in hooks
    # Release-only items are invisible to rustdoc.
    assert root + "release_only_proof" not in default
    assert default[root + "Thing::debug_impl_method"].cfg == "debug_assertions"
    assert default[root + "Thing::get"].cfg is None

    broken = doc("base-default")
    for item in broken["index"].values():
        if item["name"] == "debug_only_for_test":
            item["attrs"] = [{"other": "#[attr = CfgTrace([Unknown(1)])]"}]
    expect_error(tool, lambda: tool.walk(broken), "cfg")


def test_move_and_renumbering_equal(tool: ModuleType) -> None:
    base = tool.rustdoc_entries(doc("base-default"))
    assert len(base) > 50
    # The moved variant also moves `cfg`/`doc(hidden)` sites between a
    # definition and its re-export (`plain_target`, `debug_reexported`).
    moved = tool.rustdoc_entries(doc("moved-default"))
    assert entry_keys(base) == entry_keys(moved), (
        sorted(entry_keys(base) - entry_keys(moved))[:5],
        sorted(entry_keys(moved) - entry_keys(base))[:5],
    )
    assert entry_keys(base) == entry_keys(
        tool.rustdoc_entries(renumbered(doc("base-default")))
    )
    facade = tool.rustdoc_entries(doc("facade-default"))
    facade_moved = tool.rustdoc_entries(doc("facade-moved-default"))
    assert facade == facade_moved
    facade_paths = {e["path"]: e for e in facade}
    thing = facade_paths["hs_facade::Thing"]
    assert thing["kind"] == "external"
    assert json.loads(thing["signature"]) == {
        "source": "hs_fixture::Thing",
        "cfg": None,
        "hidden": False,
    }
    debug = json.loads(facade_paths["hs_facade::debug_only_for_test"]["signature"])
    assert debug == {
        "source": "hs_fixture::debug_only_for_test",
        "cfg": "debug_assertions",
        "hidden": True,
    }
    assert (
        facade_paths["hs_facade::external-glob:hs_fixture::cyc"]["kind"]
        == "external-glob"
    )
    assert (
        json.loads(facade_paths["hs_facade::facade_absence_proof"]["signature"])["cfg"]
        == 'not(feature = "hooks")'
    )


def test_difference_classes(tool: ModuleType) -> None:
    base = tool.rustdoc_entries(doc("base-default"))
    changed = tool.rustdoc_entries(doc("changed-default"))
    result = tool.compare(
        manifest(tool, {"base": base}), manifest(tool, {"base": changed})
    )
    assert result["equal"] is False and not result["metadata_diffs"]
    (row,) = result["row_diffs"]
    added = {(e["path"], e["kind"]) for e in row["added"]}
    removed = {(e["path"], e["kind"]) for e in row["removed"]}
    root = "hs_fixture::"
    expected_paths = {
        root + name
        for name in (
            "make_alias",
            "make_alias2",
            "KindProbe",
            "sig_probe",
            "vis_probe",
            "own_hidden_probe",
            "use_hidden_probe",
            "ImplProbe::method",
            "cfg_probe",
            "cfg_drop_probe",
            "cfg_narrow_probe",
            "gate_both_probe",
        )
    }
    assert {path for path, _ in added | removed} == expected_paths, (added, removed)
    assert (root + "make_alias", "function") in removed
    assert (root + "make_alias2", "function") in added
    assert (root + "KindProbe", "struct") in removed
    assert (root + "KindProbe", "enum") in added
    assert (root + "vis_probe", "function") in removed
    assert (root + "vis_probe", "function") not in added
    before = {e["path"]: json.loads(e["signature"]) for e in base}
    after = {e["path"]: json.loads(e["signature"]) for e in changed}

    def only_field_changed(name: str, field: str, old: Any, new: Any) -> None:
        was, now = before[root + name], after[root + name]
        assert (was[field], now[field]) == (old, new), (name, was[field], now[field])
        assert {k: v for k, v in was.items() if k != field} == {
            k: v for k, v in now.items() if k != field
        }, name

    assert before[root + "sig_probe"]["inner"] != after[root + "sig_probe"]["inner"]
    # Effective hidden: set at the definition, the re-export, and the impl.
    only_field_changed("own_hidden_probe", "hidden", False, True)
    only_field_changed("use_hidden_probe", "hidden", False, True)
    only_field_changed("ImplProbe::method", "hidden", False, True)
    # Effective cfg: widened, dropped, narrowed, and dropped from both sites.
    only_field_changed(
        "cfg_probe", "cfg", "debug_assertions", "any(debug_assertions, test)"
    )
    only_field_changed("cfg_drop_probe", "cfg", "debug_assertions", None)
    only_field_changed(
        "cfg_narrow_probe",
        "cfg",
        'any(debug_assertions, feature = "hooks")',
        "debug_assertions",
    )
    only_field_changed("gate_both_probe", "cfg", "debug_assertions", None)
    changed_paths = {item["path"] for item in row["changed"]}
    assert {
        root + n
        for n in ("sig_probe", "own_hidden_probe", "cfg_probe", "gate_both_probe")
    } <= changed_paths


def test_test_inventory(tool: ModuleType) -> None:
    recorded = json.loads((JSON / "inventory-base-hooks.json").read_text())
    messages = "".join(json.dumps(m) + "\n" for m in recorded["messages"])

    def lister(executable: str) -> tuple[str, str]:
        listing = recorded["listings"][executable]
        return listing["list"], listing["ignored"]

    entries = tool.inventory_entries(messages, lister)
    keyed = {(e["path"], e["kind"]): e["signature"] for e in entries}
    assert keyed == {
        ("lib::tests::unit_in_lib", "test"): "run",
        ("hooked::hooked", "test"): "run",
        ("plain::ignored_by_design", "test"): "ignored",
        ("plain::runs", "test"): "run",
        ("plain::second", "test"): "run",
        ("platform::on_unix", "test"): "run",
        ("required::required", "test"): "run",
        ("broken", "test-build"): "failed",
    }, keyed

    # One test removed, one newly ignored, one added: remove, change, add.
    edited = copy.deepcopy(recorded)
    plain = edited["listings"]["/FIXTURE/exe/test-plain"]
    plain["list"] = "added_later: test\nignored_by_design: test\nruns: test\n"
    plain["ignored"] = "ignored_by_design: test\nruns: test\n"

    def edited_lister(executable: str) -> tuple[str, str]:
        listing = edited["listings"][executable]
        return listing["list"], listing["ignored"]

    after = tool.inventory_entries(messages, edited_lister)
    result = tool.compare(
        manifest(tool, {"tests-base": entries}), manifest(tool, {"tests-base": after})
    )
    (row,) = result["row_diffs"]
    # The shared compare keys entries by signature too, so a status change is
    # also one raw removal plus one raw addition, paired under `changed`.
    assert sorted(e["path"] for e in row["added"]) == [
        "plain::added_later",
        "plain::runs",
    ]
    assert sorted(e["path"] for e in row["removed"]) == ["plain::runs", "plain::second"]
    assert [
        (c["before"]["signature"], c["after"]["signature"])
        for c in row["changed"]
        if c["path"] == "plain::runs"
    ] == [("run", "ignored")]
    # An error without an executable for another target fails closed.
    expect_error(
        tool,
        lambda: tool.inventory_entries(
            json.dumps(
                {
                    "reason": "compiler-message",
                    "target": {"kind": ["lib"], "name": "x"},
                    "message": {"level": "error", "message": "boom"},
                }
            )
            + "\n",
            lister,
        ),
        "lib",
    )


def fixture_workspace(directory: Path) -> Path:
    import shutil

    root = directory / "crate"
    shutil.copytree(FIXTURES / "crate", root)
    return root


def test_test_targets_row(tool: ModuleType) -> None:
    with tempfile.TemporaryDirectory() as directory:
        root = fixture_workspace(Path(directory))
        entries = tool.test_target_entries(root)
        keyed = {e["path"]: json.loads(e["signature"]) for e in entries}
        assert {e["kind"] for e in entries} == {"test-target"}
        assert keyed == {
            "hs_fixture::broken": {
                "cfg": None,
                "required_features": [],
                "source": "tests/broken.rs",
            },
            "hs_fixture::extra": {
                "cfg": 'all(feature = "extra", feature = "hooks")',
                "required_features": [],
                "source": "tests/extra.rs",
            },
            "hs_fixture::hooked": {
                "cfg": 'feature = "hooks"',
                "required_features": [],
                "source": "tests/hooked.rs",
            },
            "hs_fixture::platform": {
                "cfg": "unix",
                "required_features": [],
                "source": "tests/platform.rs",
            },
            "hs_fixture::plain": {
                "cfg": None,
                "required_features": [],
                "source": "tests/plain.rs",
            },
            "hs_fixture::required": {
                "cfg": None,
                "required_features": ["hooks"],
                "source": "tests/required.rs",
            },
        }, keyed
        rows = tool.inventory_rows(
            root, [{"id": "fx-default", "crate": "hs_fixture", "features": []}]
        )
        assert [(r["id"], r["crate"], r["features"]) for r in rows] == [
            ("tests-fx-default", "hs_fixture", []),
            ("tests-req-hs_fixture--extra", "hs_fixture", ["extra"]),
            ("tests-req-hs_fixture--hooks", "hs_fixture", ["hooks"]),
        ]

        # A dropped target, a renamed target, and a changed requirement differ.
        (root / "tests" / "plain.rs").unlink()
        (root / "tests" / "hooked.rs").rename(root / "tests" / "hooked_renamed.rs")
        manifest_text = (root / "Cargo.toml").read_text()
        (root / "Cargo.toml").write_text(
            manifest_text.replace(
                'required-features = ["hooks"]', 'required-features = ["extra"]'
            )
        )
        after = tool.test_target_entries(root)
        result = tool.compare(
            manifest(tool, {"test-targets": entries}),
            manifest(tool, {"test-targets": after}),
        )
        (row,) = result["row_diffs"]
        # A changed requirement is a raw removal plus addition, paired as changed.
        assert sorted(e["path"] for e in row["added"]) == [
            "hs_fixture::hooked_renamed",
            "hs_fixture::required",
        ]
        assert sorted(e["path"] for e in row["removed"]) == [
            "hs_fixture::hooked",
            "hs_fixture::plain",
            "hs_fixture::required",
        ]
        assert "hs_fixture::required" in [c["path"] for c in row["changed"]]


def test_compare_contract(tool: ModuleType) -> None:
    entry = {"path": "a::b", "kind": "function", "signature": "{}"}
    other = {"path": "a::c", "kind": "function", "signature": "{}"}
    changed = {"path": "a::b", "kind": "function", "signature": '{"x":1}'}
    base = manifest(tool, {"engine-default": [entry], "facade-default": [entry]})
    same = manifest(
        tool,
        {"engine-default": [entry], "facade-default": [entry]},
        capture_source_sha=OTHER_SHA,
    )
    result = tool.compare(base, same)
    assert result["equal"] is True and result["provenance"]["same_source"] is False
    diff = tool.compare(
        base,
        manifest(tool, {"engine-default": [entry, other], "facade-default": [changed]}),
    )
    rows = {row["row"]: row for row in diff["row_diffs"]}
    assert rows["engine-default"]["added"] == [other]
    assert rows["facade-default"]["changed"][0]["after"] == changed
    removed = tool.compare(
        base, manifest(tool, {"engine-default": [], "facade-default": [entry]})
    )
    assert removed["row_diffs"][0]["removed"] == [entry]
    for key, value in (
        ("rustdoc_format_version", 58),
        ("target", "aarch64-unknown-linux-gnu"),
        ("tools", {"rust-toolchain": "nightly-2099-01-01", "rustc": "x"}),
        ("row_identities", [{"id": "engine-default"}]),
    ):
        mismatch = tool.compare(
            base,
            manifest(
                tool,
                {"engine-default": [entry], "facade-default": [entry]},
                **{key: value},
            ),
        )
        assert mismatch["equal"] is False and key in mismatch["metadata_diffs"], key
    slice30 = copy.deepcopy(base)
    slice30["metadata"]["schema"] = "fathomdb.surface-baseline.v1"
    expect_error(tool, lambda: tool.compare(slice30, base), "schema")
    expect_error(tool, lambda: tool.compare(base, slice30), "schema")

    with tempfile.TemporaryDirectory() as directory:
        a = Path(directory) / "a.json"
        b = Path(directory) / "b.json"
        c = Path(directory) / "c.json"
        a.write_text(json.dumps(base))
        b.write_text(
            json.dumps(
                manifest(tool, {"engine-default": [other], "facade-default": [entry]})
            )
        )
        c.write_text(json.dumps(slice30))
        before = (a.read_bytes(), b.read_bytes())
        with mock.patch("sys.stdout"):
            assert (
                tool.main(["compare", "--baseline", str(a), "--candidate", str(a)]) == 0
            )
            assert (
                tool.main(["compare", "--baseline", str(a), "--candidate", str(b)]) == 1
            )
        with mock.patch("sys.stderr"):
            assert (
                tool.main(["compare", "--baseline", str(c), "--candidate", str(a)]) == 2
            )
        assert (a.read_bytes(), b.read_bytes()) == before


def test_output_guards(tool: ModuleType) -> None:
    with tempfile.TemporaryDirectory() as directory:
        target = Path(directory) / "out.json"
        tool.exclusive_write(target, "first\n")
        assert target.read_text() == "first\n"
        # Committed baselines get ordinary umask-derived permissions, not the
        # 0600 of the private temporary file they are linked from.
        umask = os.umask(0)
        os.umask(umask)
        assert target.stat().st_mode & 0o777 == 0o666 & ~umask, oct(
            target.stat().st_mode
        )
        expect_error(tool, lambda: tool.exclusive_write(target, "second\n"), "exists")
        assert target.read_text() == "first\n"
        assert sorted(p.name for p in Path(directory).iterdir()) == ["out.json"]
    inside = tool.BASELINE_DIR / "baseline-injected.json"
    expect_error(
        tool, lambda: tool.guard_output(inside, source_modified=True), "source_modified"
    )
    expect_error(
        tool,
        lambda: tool.guard_output(
            tool.BASELINE_DIR / "sub" / ".." / "x.json", source_modified=True
        ),
        "source_modified",
    )
    tool.guard_output(inside, source_modified=False)
    tool.guard_output(Path("/tmp/claude-scratch/x.json"), source_modified=True)
    exports = tool.OWNED_ROOT / "exports"
    tool.validate_source_dir(exports / f"{SHA}-1", must_exist=False)
    for bad in (
        tool.OWNED_ROOT / "src",
        Path("/tmp/elsewhere") / f"{SHA}-1",
        exports / "not-a-sha-1",
        exports / f"{SHA}-1" / "..",
    ):
        expect_error(
            tool,
            lambda bad=bad: tool.validate_source_dir(bad, must_exist=False),
            "source-dir",
        )


def test_source_sha_validation(tool: ModuleType) -> None:
    head = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    ).stdout.strip()
    tree = subprocess.run(
        ["git", "rev-parse", "HEAD^{tree}"],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=True,
    ).stdout.strip()
    assert tool.validate_source_sha(head) == head
    expect_error(tool, lambda: tool.validate_source_sha(head[:12]), "40")
    expect_error(tool, lambda: tool.validate_source_sha(head.upper()), "40")
    expect_error(tool, lambda: tool.validate_source_sha("0" * 40), "commit")
    expect_error(tool, lambda: tool.validate_source_sha(tree), "commit")

    # A bad SHA fails before any toolchain, export, or build command runs.
    calls: list[list[str]] = []
    real_run = tool._run

    def recording_run(command: list[str], cwd: Path, env: Any = None) -> str:
        calls.append(list(command))
        if command[0] != "git":
            raise AssertionError(f"non-git command before validation: {command}")
        return real_run(command, cwd, env)

    with tempfile.TemporaryDirectory() as directory:
        output = Path(directory) / "out.json"
        for bad in (head[:12], "0" * 40, tree):
            with (
                mock.patch.object(tool, "_run", recording_run),
                mock.patch("sys.stderr"),
            ):
                assert (
                    tool.main(["capture", "--source-sha", bad, "--output", str(output)])
                    == 2
                )
        assert not output.exists()
    assert all(command[:2] == ["git", "cat-file"] for command in calls), calls


def test_git_is_read_only(tool: ModuleType) -> None:
    assert tool.GIT_SUBCOMMANDS == frozenset({"archive", "cat-file"})
    for forbidden in ("stash", "worktree", "checkout", "reset", "update-ref", "add"):
        expect_error(tool, lambda forbidden=forbidden: tool._git([forbidden]), "git")


def test_toolchain_and_format_checks(tool: ModuleType) -> None:
    def missing(command: list[str], cwd: Path, env: Any = None) -> str:
        raise tool.HiddenSurfaceError(f"command failed: {' '.join(command)}")

    with mock.patch.object(tool, "_run", missing):
        expect_error(tool, tool.check_toolchain, tool.PINNED_NIGHTLY)

    good = doc("facade-default")
    assert good["format_version"] == tool.FORMAT_VERSION == 57
    bad = copy.deepcopy(good)
    bad["format_version"] = 56
    with tempfile.TemporaryDirectory() as directory:
        path = Path(directory) / "hs_facade.json"
        path.write_text(json.dumps(bad))
        expect_error(tool, lambda: tool.load_rustdoc(path), "format_version")
        path.write_text(json.dumps(good))
        assert tool.load_rustdoc(path)["format_version"] == 57

        # A capture failure writes no output.
        output = Path(directory) / "never.json"
        with (
            mock.patch.object(tool, "validate_source_sha", lambda sha: sha),
            mock.patch.object(
                tool,
                "capture_source_sha",
                mock.Mock(side_effect=tool.HiddenSurfaceError("format_version 56")),
            ),
            mock.patch("sys.stderr"),
        ):
            assert (
                tool.main(["capture", "--source-sha", SHA, "--output", str(output)])
                == 2
            )
        assert not output.exists()


def test_release_probe(tool: ModuleType) -> None:
    fixture_items = tool.select_probe_items(
        tool.walk(doc("base-default")),
        [{"path": "hs_fixture::release_only_proof", "kind": "module"}],
    )
    assert [(i.path, i.kind, i.form, i.expected) for i in fixture_items] == [
        ("hs_fixture::Thing::debug_impl_method", "function", "value", "unresolved"),
        (
            "hs_fixture::Thing::impl hs_fixture::DebugOnlyTrait",
            "impl",
            "bound",
            "unresolved",
        ),
        ("hs_fixture::all_gate", "function", "use", "unresolved"),
        ("hs_fixture::any_gate", "function", "use", "unresolved"),
        ("hs_fixture::cfg_drop_probe", "function", "use", "unresolved"),
        ("hs_fixture::cfg_narrow_probe", "function", "use", "unresolved"),
        ("hs_fixture::cfg_probe", "function", "use", "unresolved"),
        ("hs_fixture::debug_only_for_test", "function", "use", "unresolved"),
        ("hs_fixture::debug_reexported", "function", "use", "unresolved"),
        ("hs_fixture::gate_both_probe", "function", "use", "unresolved"),
        ("hs_fixture::release_only_proof", "module", "use", "resolved"),
    ]
    facade_items = tool.select_probe_items(
        tool.walk(doc("facade-default")),
        [{"path": "hs_facade::facade_release_proof", "kind": "module"}],
    )
    for crate, items in (("hs_fixture", fixture_items), ("hs_facade", facade_items)):
        source, ranges = tool.generate_probe(items)
        assert source == (FIXTURES / "probe" / f"{crate}.rs").read_text(), crate
        recorded = (JSON / f"probe-{crate}.jsonl").read_text()
        statuses = tool.probe_statuses(recorded, ranges)
        assert statuses == [item.expected for item in items], (crate, statuses)
        entries = tool.probe_row_entries(items, statuses)
        assert [(e["path"], e["kind"], e["signature"]) for e in entries] == [
            (item.path, "release-probe", item.expected) for item in items
        ]
        flipped = ["resolved" if s == "unresolved" else "unresolved" for s in statuses]
        expect_error(
            tool,
            lambda items=items, flipped=flipped: tool.probe_row_entries(items, flipped),
            "release probe",
        )

    source, ranges = tool.generate_probe(fixture_items)
    recorded = (JSON / "probe-hs_fixture.jsonl").read_text()
    # An error outside every probe function, or with an unexpected code, fails closed.
    first = json.loads(recorded.splitlines()[0])
    stray = copy.deepcopy(first)
    for span in stray["message"]["spans"]:
        span["line_start"] = span["line_end"] = 1
    expect_error(
        tool, lambda: tool.probe_statuses(json.dumps(stray) + "\n", ranges), "probe"
    )
    odd = copy.deepcopy(first)
    odd["message"]["code"] = {"code": "E0603", "explanation": None}
    expect_error(
        tool, lambda: tool.probe_statuses(json.dumps(odd) + "\n", ranges), "E0603"
    )
    # A build error in any target other than the probe fails closed.
    elsewhere = copy.deepcopy(first)
    elsewhere["target"]["name"] = "fathomdb_engine"
    expect_error(
        tool,
        lambda: tool.probe_statuses(json.dumps(elsewhere) + "\n", ranges),
        "outside the probe",
    )

    # Items the release probe cannot name fail closed instead of being skipped.
    unsupported = copy.deepcopy(fixture_items[0])
    unsupported.form = None
    expect_error(tool, lambda: tool.generate_probe([unsupported]), "probe")


def test_release_probe_owner_gated_impls(tool: ModuleType) -> None:
    """A trait impl gated only through its owner type is probed by naming the
    owner; canonical trait paths can be private or unstable (for example
    `core::ops::drop::Drop`, `core::marker::StructuralPartialEq`)."""

    gated = doc("base-default")
    thing = next(
        item
        for item in gated["index"].values()
        if item["name"] == "Thing" and "struct" in item["inner"]
    )
    thing["attrs"].append(
        {
            "other": '#[attr = CfgTrace([NameValue { name: "debug_assertions", '
            "value: None, span: src/inner.rs:1:7: 1:23 (#0) }])]"
        }
    )
    items = {item.path: item for item in tool.select_probe_items(tool.walk(gated), [])}
    clone = items["hs_fixture::Thing::impl core::clone::Clone"]
    # Fields inherit the parent type's effective cfg and hidden flag.
    records = by_path(tool.walk(gated))
    field = sig(records["hs_fixture::Thing::x"])
    assert (field["hidden"], field["cfg"]) == (False, "debug_assertions"), field
    fields = sig(records["hs_fixture::Thing"])["inner"]["struct"]["kind"]["plain"][
        "fields"
    ]
    assert ["x", False, "debug_assertions"] in fields, fields
    hidden_parent = doc("base-default")
    thing_item = next(
        item
        for item in hidden_parent["index"].values()
        if item["name"] == "Thing" and "struct" in item["inner"]
    )
    thing_item["attrs"].append({"other": "#[doc(hidden)]"})
    hidden_records = by_path(tool.walk(hidden_parent))
    assert sig(hidden_records["hs_fixture::Thing::x"])["hidden"] is True
    hidden_fields = sig(hidden_records["hs_fixture::Thing"])["inner"]["struct"]["kind"][
        "plain"
    ]["fields"]
    assert ["x", True, None] in hidden_fields, hidden_fields
    assert (clone.form, clone.owner_path) == ("owner", "hs_fixture::Thing")
    # Owner-gated wins over an impl-site gate: the owner's absence suffices.
    assert items["hs_fixture::Thing::impl hs_fixture::DebugOnlyTrait"].form == "owner"
    assert items["hs_fixture::Thing::get"].form == "value"
    assert items["hs_fixture::Thing"].form == "use"
    source, ranges = tool.generate_probe([clone])
    assert "    use hs_fixture::Thing as _;\n" in source
    assert "// hs_probe 0: impl hs_fixture::Thing::impl core::clone::Clone\n" in source
    assert len(ranges) == 1


def test_release_only_scan(tool: ModuleType) -> None:
    sources = {
        "lib.rs": (
            "#[cfg(not(debug_assertions))]\n"
            "#[doc(hidden)]\n"
            "pub mod release_surface_raw_sql_absence_proof {}\n"
            "#[cfg(not(debug_assertions))]\n"
            "fn private_release_helper() {}\n"
            "#[cfg(not(debug_assertions))]\n"
            "pub(crate) fn crate_release_helper() {}\n"
            "#[cfg(debug_assertions)]\n"
            "pub fn debug_only() {}\n"
        )
    }
    assert tool.release_only_names(sources) == {"release_surface_raw_sql_absence_proof"}
    curated = [
        {"path": "fathomdb::release_surface_raw_sql_absence_proof", "kind": "module"}
    ]
    tool.check_release_only(sources, curated)
    # The cfg is evaluated, not substring-matched: `not(any(test,
    # debug_assertions))` is release-only; a cfg that merely mentions
    # `not(debug_assertions)` inside a debug-true disjunction is not.
    evaluated = {
        "a.rs": (
            "#[cfg(not(any(test, debug_assertions)))]\npub fn nested_release_only() {}\n"
            "#[cfg(any(debug_assertions, not(debug_assertions)))]\npub fn always() {}\n"
        )
    }
    assert tool.release_only_names(evaluated) == {"nested_release_only"}
    extra = dict(sources)
    extra["other.rs"] = (
        '#[cfg(all(feature = "x", not(debug_assertions)))]\n'
        "/// docs\n"
        "#[inline]\n"
        "pub fn surprise_release_only() {}\n"
    )
    expect_error(
        tool, lambda: tool.check_release_only(extra, curated), "surprise_release_only"
    )
    # `test` is false in a release build, never a free atom: an item gated on
    # `all(test, not(debug_assertions))` exists in no release build.
    test_only = {"t.rs": "#[cfg(all(test, not(debug_assertions)))]\npub fn t() {}\n"}
    assert tool.release_only_names(test_only) == set()
    # A cfg quoted in documentation gates nothing and is not parsed; an
    # unparseable cfg that does gate a public item still fails closed.
    documented = {
        "d.rs": (
            "/// Callers gate this with `#[cfg(feature = ...)]` themselves.\n"
            "pub fn documented() {}\n"
        )
    }
    assert tool.release_only_names(documented) == set()
    broken = {"b.rs": "#[cfg(feature = ...)]\npub fn broken() {}\n"}
    expect_error(tool, lambda: tool.release_only_names(broken), "release-only scan")


def test_capacity_and_prune_lock(tool: ModuleType) -> None:
    usage = mock.Mock(return_value=SimpleNamespace(free=tool.MIN_FREE_BYTES - 1))
    with mock.patch.object(tool.shutil, "disk_usage", usage):
        expect_error(tool, tool._check_capacity, "required")
    usage = mock.Mock(return_value=SimpleNamespace(free=tool.MIN_FREE_BYTES))
    with mock.patch.object(tool.shutil, "disk_usage", usage):
        tool._check_capacity()
    # prune takes the owned-root lock before it deletes anything.
    events: list[str] = []
    with tempfile.TemporaryDirectory() as directory:
        root = Path(directory) / "root"
        cache = Path(directory) / "cache" / "target"
        cache.mkdir(parents=True)

        class Lock:
            def __enter__(self) -> None:
                events.append("lock")

            def __exit__(self, *args: Any) -> None:
                events.append("unlock")

        real_rmtree = tool.shutil.rmtree

        def rmtree(path: Any, *args: Any, **kwargs: Any) -> None:
            events.append("rmtree")
            real_rmtree(path, *args, **kwargs)

        with (
            mock.patch.object(tool, "OWNED_ROOT", root),
            mock.patch.object(tool, "OWNED_CACHE", cache),
            mock.patch.object(tool, "_owned_lock", Lock),
            mock.patch.object(tool.shutil, "rmtree", rmtree),
        ):
            root.mkdir()
            tool.prune()
        assert events[0] == "lock" and "rmtree" in events, events
        assert not cache.exists()


def test_rows_and_wiring(tool: ModuleType) -> None:
    assert [row["id"] for row in tool.ROWS] == [
        "engine-default",
        "engine-test-hooks",
        "engine-slice72-test-hooks",
        "engine-operator-test-hooks",
        "engine-migration-test-hooks",
        "engine-tc5-benchmark",
        "facade-default",
        "facade-operator",
    ]
    features = {row["id"]: row["features"] for row in tool.ROWS}
    assert features["engine-operator-test-hooks"] == ["operator", "test-hooks"]
    assert features["engine-default"] == [] and features["facade-operator"] == [
        "operator"
    ]
    assert tool.RELEASE_PROBE_ROW == "release-probe"
    assert tool.SCHEMA == "fathomdb.hidden-surface.v1"
    assert tool.PINNED_NIGHTLY == "nightly-2026-04-24"
    assert str(tool.OWNED_ROOT) == "/tmp/fathomdb-0.8.27-hidden-surface"
    assert tool.OWNED_CACHE == ROOT / ".cache" / "0.8.27-hidden-surface" / "target"
    for row in tool.ROWS:
        arguments = tool.rustdoc_arguments(row)
        assert not any(os.path.isabs(arg) for arg in arguments), arguments
        assert arguments[:4] == ["cargo", "+nightly-2026-04-24", "rustdoc", "--locked"]
        assert arguments[-5:] == [
            "-Z",
            "unstable-options",
            "--output-format",
            "json",
            "--document-hidden-items",
        ]
        inventory = tool.inventory_arguments(row)
        assert not any(os.path.isabs(arg) for arg in inventory), inventory
        assert inventory[:7] == [
            "cargo",
            "+nightly-2026-04-24",
            "build",
            "--locked",
            "-p",
            row["crate"],
            "--no-default-features",
        ]
        assert inventory[-4:] == ["--tests", "--keep-going", "--message-format", "json"]
    identities = {
        r["id"]: r
        for r in tool.row_identities(
            [{"id": "tests-req-x--a+b", "crate": "x", "features": ["a", "b"]}]
        )
    }
    assert set(identities) == (
        {row["id"] for row in tool.ROWS}
        | {"tests-" + row["id"] for row in tool.ROWS}
        | {"release-probe", "test-targets", "tests-req-x--a+b"}
    )
    assert identities["tests-req-x--a+b"]["features"] == ["a", "b"]
    assert identities["tests-req-x--a+b"]["profile"] == "test"
    agent_test = (ROOT / "scripts" / "agent-test.sh").read_text()
    assert (
        "run_tier_suite fast test-hidden-surface python3 scripts/tests/test_hidden_surface.py"
        in agent_test
    )


def main() -> None:
    tool = load_tool()
    tests = [
        test_cfg_parser,
        test_walk_hazards,
        test_cfg_canonical_form,
        test_effective_values,
        test_move_and_renumbering_equal,
        test_difference_classes,
        test_test_inventory,
        test_test_targets_row,
        test_compare_contract,
        test_output_guards,
        test_source_sha_validation,
        test_git_is_read_only,
        test_toolchain_and_format_checks,
        test_release_probe,
        test_release_probe_owner_gated_impls,
        test_release_only_scan,
        test_capacity_and_prune_lock,
        test_rows_and_wiring,
    ]
    for test in tests:
        test(tool)
        print(f"ok    {test.__name__}")
    print("ok    hidden-surface")


if __name__ == "__main__":
    main()
