// FathomDB TypeScript SDK public package root.
export * from "./errors.js";
export { read } from "./read.js";
export type {
  BoundaryCrossing,
  NodeRecord,
  OperationalStateRecordV1,
  OpStoreRow,
  PageCursor,
  PageRequestV1,
  PageV1,
  Predicate,
  ReadCollectionOptions,
  ReadView,
} from "./read.js";

export {
  LifecycleState,
  WriteReceipt,
  WholeBodySourceLocator,
  Utf8BytesSourceLocator,
  SourceLocator,
  CanonicalHash,
  CanonicalWriteProvenanceV1,
  DerivedWriteProvenanceV1,
  WriteProvenanceV1,
  SourceDependencyRegistrationV1,
  DependencySourceLookupV1,
  DependencyDerivedLookupV1,
  SourceDependencyV1,
  DependencyListV1,
  ClosureLookupV1,
  ClosureProofV1,
  ClosureStatusV1,
  ActuationOperationV1,
  ActuationBatchV1,
  ActuationReceiptV1,
  EraseReport,
  IngestWithExtractorReceipt,
  ExtractDocument,
  ConsolidateReceipt,
  ConsolidateAxis,
} from "./write.js";
export { embedBatchCls, RerankPassage, RerankOptions, RerankResult, rerank } from "./embedding.js";
export { EngineConfig, EngineOpenOptions, Engine } from "./core.js";
export {
  ProjectionReadinessV1,
  ProjectionRuntimeStateV1,
  ProjectionGenerationOriginV1,
  ProjectionGenerationStatusV1,
  MutationProjectionStatusRequestV1,
  MutationProjectionStatusV1,
  ProjectionRole,
  ProjectionSpec,
  DenseReadiness,
  ProjectionDelta,
  ProjectionRuntimeUnavailabilityReason,
  ProjectionStatusDenseReadiness,
  ProjectionRuntimeStatusEntry,
  ProjectionRuntimeStatus,
  EmbeddingReadinessState,
  EmbeddingOperation,
  EmbeddingReadiness,
} from "./projection.js";
export {
  SoftFallbackBranch,
  SoftFallback,
  IdSpace,
  SearchHit,
  SearchFilter,
  ReadContextV1,
  FrozenReadContextV1,
  FrozenSearchOptions,
  SearchOptions,
  SearchExpandOptions,
  mapNativeSearchResult,
  FilterTerm,
  Filter,
  filterToSearchFilter,
  searchFilterToFilter,
  QueryTrace,
  PerHitExplain,
  StructuralInclusionStateV1,
  StructuralProjectionOriginV1,
  StructuralDependencyStateV1,
  StructuralLifecycleStateV1,
  StructuralDegradationCodeV1,
  StructuralInclusionV1,
  mapPerHitExplain,
  Explanation,
  SearchResult,
} from "./search.js";
export {
  DependencyTraceDirectionV1,
  DependencyTraceRequestV1,
  TraceNodeLifecycleV1,
  DependencyTraceNodeV1,
  DependencyTraceEdgeV1,
  TraceReadBoundaryV1,
  DependencyTraceResultV1,
  EvidenceSearchRequestV1,
  EvidenceResolveRequestV1,
  EvidenceSidecarEntryV1,
  EvidenceContributionV1,
  EvidenceGraphOriginV1,
  EvidenceProjectionOriginV1,
  EvidenceArtifactLifecycleV1,
  EvidenceSearchResultV1,
  ResolvedEvidenceV1,
  validateDependencyTraceResponse,
} from "./evidence.js";
export {
  MigrationStepReport,
  EmbedderIdentity,
  DefaultEmbedderDownloadEvent,
  DefaultEmbedderCacheHitEvent,
  MeanVecPinnedEvent,
  UnknownEmbedderEvent,
  EmbedderEvent,
  isKnownEmbedderEvent,
  mapEmbedderEvent,
  OpenReport,
  GpuAllocationWitness,
  CudaAllocatorReport,
  CudaDeviceInfo,
  CudaVisibleDevice,
  EffectiveEmbedDevice,
  DeviceResolution,
  mapOpenReport,
  CounterSnapshot,
  SubscriberEvent,
  SubscriberCallback,
} from "./open.js";
export { AdminConfigureOptions, RuntimeSqliteMode, RuntimeConfigureOptions, RuntimeConfiguration, admin } from "./admin.js";
export {
  ExpandedNode,
  SearchExpandResult,
  TraversalDirection,
  GraphQuerySeedV1,
  GraphExplicitSeedV1,
  GraphSeedV1,
  CurrentGraphReadContextV1,
  FrozenGraphReadContextV1,
  GraphReadContextV1,
  GraphExpandRequestV1,
  GraphEvidenceSidecarEntryV1,
  GraphEvidenceSidecarV1,
  ResolvedGraphSeedV1,
  GraphOriginV1,
  GraphTargetV1,
  GraphSeedSourceV1,
  GraphReadModeV1,
  GraphProjectionOriginV1,
  GraphProjectionReadinessV1,
  GraphExpansionDegradationCodeV1,
  GraphTargetExplanationV1,
  GraphExpansionExplanationV1,
  GraphExpandResultV1,
  GraphEvidenceResolveRequestV1,
  GraphEvidenceArtifactV1,
  ResolvedGraphEvidenceV1,
  validateGraphExpandResult,
  graph,
} from "./graph.js";
